namespace NFMWorld.LuaSourceGenerator;

internal class LuaBindingTypeGenerator(LuaVisibleType type, DiscoveredKind kind, string @namespace)
{
    // Determine if we need instance method binding implementations for inheritance
    private readonly bool _doesRequireInstanceMethodsForInheritance
        = type.IsVisibleToLua || (kind & (DiscoveredKind.BaseType | DiscoveredKind.Interface)) != 0;

    private readonly bool _doesRequireStaticMethodsForExtensions
        = type.IsVisibleToLua || (kind & (DiscoveredKind.ExtensionMethodDeclaringType)) != 0;

    private readonly bool _hasInstanceMetamethods = type.IsVisibleToLua && !type.IsStatic;
    private readonly bool _hasInstanceIndexer = type.IsVisibleToLua && (type.InstanceFields.Length > 0 || type.InstanceProperties.Length > 0 || type.InstanceIndexer != null || type.InstanceMethods.Length > 0 || type.IsArray || type.IsInlineArray) && !type.IsStatic;
    private readonly bool _hasStaticIndexer = type.IsVisibleToLua && (type.StaticFields.Length > 0 || type.StaticProperties.Length > 0 || type.StaticIndexer != null);
    private readonly bool _hasStaticMethods = type.IsVisibleToLua && (type.StaticMethods.Length > 0 || type.Constructors.Length > 0 || type.StaticEvents.Length > 0 || type.IsStruct);

    public bool HasAnythingToGenerate()
    {
        if (_doesRequireInstanceMethodsForInheritance)
        {
            if (type.DeclaredInstanceMethods.Length != 0)
                return true;

            if (type.Operators.Length != 0)
                return true;
            
            if (type.DeclaredInstanceEvents.Length != 0)
                return true;
        }

        if (_doesRequireStaticMethodsForExtensions)
        {
            if (type.DeclaredExtensionMethods.Length != 0)
                return true;
        }
        
        if (_hasInstanceMetamethods)
            return true;
        
        if (_hasInstanceIndexer)
            return true;
        
        if (_hasStaticIndexer)
            return true;
        
        if (_hasStaticMethods)
            return true;
        
        return false;
    }
    
    public string GenerateCode()
    {
        var sb = new IndentedStringBuilder();

        sb.AppendLine(
            $"""
            // <auto-generated />
            // This file is auto-generated by Maxine.Extensions.Lua.SourceGenerator.
            // ReSharper disable All
            #nullable enable

            using System.Runtime.CompilerServices;
            using System.Runtime.InteropServices;
            using LuaJIT;
            using static LuaJIT.Methods;

            namespace {@namespace};

            public unsafe partial class LuaBindings
            """);

        using (sb.Block())
        {
            sb.AppendLine($"// =========== Bindings for {type.FullName} ({type.LuaName}) ===========");

            if (_hasInstanceMetamethods || _doesRequireInstanceMethodsForInheritance)
            {
                sb.AppendLine("#region Instance Methods");
                
                // Instance Methods & Operators: only if visible to Lua
                if (_hasInstanceMetamethods)
                {
                    sb.AppendLine($"private static readonly luaL_RegManaged[] {type.Type.GetGenericTypeLuaName()}_instance_metamethods = new luaL_RegManaged[]");

                    using (sb.Block(end: "};"))
                    {
                        foreach (var group in type.Operators.GroupBy(method => method.LuaName))
                        {
                            sb.AppendLine(
                                $$"""new() { name = "{{group.Key.GetLuaMetamethodName()}}", func = &{{group.First().BindingName}} },""");
                        }

                        sb.AppendLine($$"""new() { name = "__index", func = &{{type.Type.GetGenericTypeLuaName()}}_index },""");
                        sb.AppendLine($$"""new() { name = "__newindex", func = &{{type.Type.GetGenericTypeLuaName()}}_newindex },""");
                        sb.AppendLine("""new() { name = "__gc", func = &Shared__gc },""");
                        sb.AppendLine("""new() { name = "__tostring", func = &Shared__tostring },""");
                        sb.AppendLine("""new() { name = "__len", func = &Shared__len },""");
                        sb.AppendLine("""new() { name = "__pairs", func = &Shared__pairs },""");
                    }
                }
                
                // Instance Method & Operator Implementations: only if visible to Lua or required for inheritance
                if (_doesRequireInstanceMethodsForInheritance)
                {
                    sb.AppendLine();
                    foreach (var group in type.DeclaredInstanceMethods.GroupBy(method => method.Name))
                    {
                        var methodGenerator = new LuaBindingMethodGenerator(type, group.ToArray(), false, 0);
                        sb.AppendLine(methodGenerator.GenerateCode());
                        sb.AppendLine();
                    }
                    
                    sb.AppendLine();
                    foreach (var group in type.Operators.GroupBy(method => method.Name))
                    {
                        var methodGenerator = new LuaBindingMethodGenerator(type, group.ToArray(), true, 0);
                        sb.AppendLine(methodGenerator.GenerateCode());
                        sb.AppendLine();
                    }

                    sb.AppendLine();
                    foreach (var group in type.DeclaredInstanceEvents.GroupBy(@event => @event.Name))
                    {
                        var addGenerator = new LuaBindingEventAddGenerator(type, group.First(), false, 0);
                        sb.AppendLine(addGenerator.GenerateCode());
                        sb.AppendLine();
                        
                        var removeGenerator = new LuaBindingEventRemoveGenerator(type, group.First(), false, 0);
                        sb.AppendLine(removeGenerator.GenerateCode());
                        sb.AppendLine();
                    }
                }
                
                sb.AppendLine("#endregion");
                sb.AppendLine();
            }
            
            // Static Methods
            if (!type.IsVisibleToLua && _doesRequireStaticMethodsForExtensions)
            {
                if (type.DeclaredExtensionMethods.Length > 0)
                {
                    sb.AppendLine("#region Static Methods (Extension Methods)");
                    
                    foreach (var group in type.DeclaredExtensionMethods.GroupBy(method => method.Name))
                    {
                        var methodGenerator = new LuaBindingMethodGenerator(type, group.ToArray(), true, 0);
                        sb.AppendLine(methodGenerator.GenerateCode());
                        sb.AppendLine();
                    }

                    sb.AppendLine("#endregion");
                }
            }
            else if (type.IsVisibleToLua)
            {
                if (_hasStaticMethods)
                {
                    sb.AppendLine("#region Static Methods");
                    sb.AppendLine($"private static readonly luaL_RegManaged[] {type.Type.GetGenericTypeLuaName()}_static_methods = new luaL_RegManaged[]");

                    using (sb.Block(end: "};"))
                    {
                        foreach (var group in type.StaticMethods.GroupBy(method => method.LuaName))
                        {
                            sb.AppendLine(
                                $$"""new() { name = "{{group.Key}}", func = &{{group.First().BindingName}} },""");
                        }

                        if (type.Constructors.Length > 0)
                        {
                            sb.AppendLine(
                                $$"""new() { name = "new", func = &{{type.Constructors[0].BindingName}} },""");
                        }
                        else if (type.IsStruct)
                        {
                            sb.AppendLine(
                                $$"""new() { name = "new", func = &{{type.Type.GetGenericTypeLuaName()}}_struct_new },""");
                        }

                        if (type.StaticEvents.Length > 0)
                        {
                            foreach (var group in type.StaticEvents.GroupBy(@event => @event.LuaName))
                            {
                                sb.AppendLine(
                                    $$"""new() { name = "add_{{group.Key}}", func = &{{group.First().BindingName}}_add },""");
                                sb.AppendLine(
                                    $$"""new() { name = "remove_{{group.Key}}", func = &{{group.First().BindingName}}_remove },""");
                            }
                        }
                    }

                    foreach (var group in type.StaticMethods.GroupBy(method => method.Name))
                    {
                        var methodGenerator = new LuaBindingMethodGenerator(type, group.ToArray(), true, 0);
                        sb.AppendLine(methodGenerator.GenerateCode());
                        sb.AppendLine();
                    }

                    if (type.Constructors.Length > 0)
                    {
                        sb.AppendLine();
                        var methodGenerator = new LuaBindingMethodGenerator(type, type.Constructors.ToArray(), true, 0);
                        sb.AppendLine(methodGenerator.GenerateCode());
                        sb.AppendLine();
                    }
                    else if (type.IsStruct)
                    {
                        sb.AppendLine(
                            $$"""
                              [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
                              private static int {{type.Type.GetGenericTypeLuaName()}}_struct_new(lua_State L)
                              {
                                  string? errorMsg = null;
                                  try
                                  {
                                      var argCount = lua_gettop(L);
                              
                                      var result = new {{type.Type.GetFullTypeName()}}();
                                      PushValue(L, result);
                                      return 1;
                                  }
                                  catch (System.Exception ex)
                                  {
                                      errorMsg = FormatException(ex);
                                  }
                                  if (errorMsg != null)
                                  {
                                      return luaL_error(L, errorMsg);
                                  }
                                  return Unreachable();
                              }
                              """);
                    }
                    
                    sb.AppendLine();
                    foreach (var group in type.StaticEvents.GroupBy(@event => @event.Name))
                    {
                        var addGenerator = new LuaBindingEventAddGenerator(type, group.First(), true, 0);
                        sb.AppendLine(addGenerator.GenerateCode());
                        sb.AppendLine();
                        
                        var removeGenerator = new LuaBindingEventRemoveGenerator(type, group.First(), true, 0);
                        sb.AppendLine(removeGenerator.GenerateCode());
                        sb.AppendLine();
                    }
                    
                    sb.AppendLine("#endregion");
                }
                
                if (_hasStaticIndexer)
                {
                    sb.AppendLine();
                    sb.AppendLine(
                        $$"""
                        private static readonly luaL_RegManaged[] {{type.Type.GetGenericTypeLuaName()}}_static_metamethods = new luaL_RegManaged[]
                        {
                            new() { name = "__index", func = &{{type.Type.GetGenericTypeLuaName()}}_static_index },
                            new() { name = "__newindex", func = &{{type.Type.GetGenericTypeLuaName()}}_static_newindex },
                        };
                        """
                    );
                }
            }
            
            // Instance Fields & Properties
            if (_hasInstanceIndexer)
            {
                var indexGenerator = new LuaBindingIndexGenerator(type, type.InstanceFields, type.InstanceProperties, type.InstanceIndexer, type.InstanceMethods, type.InstanceEvents, false);
                sb.AppendLine(indexGenerator.GenerateCode());
                sb.AppendLine();
                
                var newIndexGenerator = new LuaBindingNewIndexGenerator(type, type.InstanceFields, type.InstanceProperties, type.InstanceIndexer, false);
                sb.AppendLine(newIndexGenerator.GenerateCode());
                sb.AppendLine();
            }
            
            // Static Fields & Properties
            if (_hasStaticIndexer)
            {
                var indexGenerator = new LuaBindingIndexGenerator(type, type.StaticFields, type.StaticProperties, type.StaticIndexer, [], [], true);
                sb.AppendLine(indexGenerator.GenerateCode());
                sb.AppendLine();
                
                var newIndexGenerator = new LuaBindingNewIndexGenerator(type, type.StaticFields, type.StaticProperties, type.StaticIndexer, true);
                sb.AppendLine(newIndexGenerator.GenerateCode());
                sb.AppendLine();
            }
        }
        
        return sb.ToString();
    }

    public string GenerateInitializeCode()
    {
        var sb = new IndentedStringBuilder();
        sb.AppendLine($"Register(");
        using (sb.Indent())
        {
            sb.AppendLine("L,");
            sb.AppendLine($"\"{type.LuaName}\",");
            sb.AppendLine($"\"{type.MetatableName}\",");

            if (_hasInstanceMetamethods)
            {
                sb.AppendLine($"{type.Type.GetGenericTypeLuaName()}_instance_metamethods,");
            }
            else
            {
                sb.AppendLine("null,");
            }

            if (_hasStaticMethods)
            {
                sb.AppendLine($"{type.Type.GetGenericTypeLuaName()}_static_methods,");
            }
            else
            {
                sb.AppendLine("null,");
            }

            if (_hasStaticIndexer)
            {
                sb.AppendLine($"{type.Type.GetGenericTypeLuaName()}_static_metamethods");
            }
            else
            {
                sb.AppendLine("null");
            }
        }

        sb.AppendLine(");");

        if (type.IsVisibleToLua && !type.IsStatic)
        {
            sb.AppendLine($"RegisterMetatable<{type.Type.GetFullTypeName()}>(\"{type.MetatableName}\");");
        }
        
        return sb.ToString();
    }

    public bool HasInitializeCode()
    {
        return type.IsVisibleToLua && HasAnythingToGenerate();
    }
}