using NFMWorld.LuaSourceGenerator.Test.SampleTypes;

namespace NFMWorld.LuaSourceGenerator.Test;

/// <summary>
/// Integration tests that generate actual code and verify it can be used.
/// </summary>
[TestFixture]
public class GeneratedCodeIntegrationTests
{
    private string _generatedCode = "";

    [OneTimeSetUp]
    public void Setup()
    {
        // Generate code once for all tests in this fixture
        var generator = new LuaBindingGenerator();
        var assemblies = new[] { typeof(SampleClass).Assembly };
        _generatedCode = generator.Generate(assemblies);
    }

    [Test]
    public void GeneratedCode_IsNotEmpty()
    {
        Assert.That(_generatedCode, Is.Not.Empty);
    }

    [Test]
    public void GeneratedCode_HasAutoGeneratedHeader()
    {
        Assert.That(_generatedCode, Does.StartWith("// <auto-generated />"));
    }

    [Test]
    public void GeneratedCode_HasRequiredUsings()
    {
        // Base usings are now in LuaBindingsBase.cs, generated code only needs Lua usings
        Assert.That(_generatedCode, Does.Contain("using LuaNET.LuaJIT;"));
        Assert.That(_generatedCode, Does.Contain("using static LuaNET.LuaJIT.Lua;"));
    }

    [Test]
    public void GeneratedCode_RegistersAllTestTypes()
    {
        // Should have registration calls for all test types
        Assert.That(_generatedCode, Does.Contain("Register_NFMWorld_LuaSourceGenerator_Test_SampleTypes_SampleClass"));
        Assert.That(_generatedCode, Does.Contain("Register_NFMWorld_LuaSourceGenerator_Test_SampleTypes_SampleStruct"));
        Assert.That(_generatedCode, Does.Contain("Register_NFMWorld_LuaSourceGenerator_Test_SampleTypes_Vector3Struct"));
    }

    [Test]
    public void GeneratedCode_SampleClass_HasCorrectStaticMethods()
    {
        Assert.That(_generatedCode, Does.Contain("_static_add"));
        Assert.That(_generatedCode, Does.Contain("_static_concat"));
        Assert.That(_generatedCode, Does.Contain("_static_incrementCounter"));
    }

    [Test]
    public void GeneratedCode_SampleClass_HasCorrectInstanceMethods()
    {
        Assert.That(_generatedCode, Does.Contain("_method_getDoubleId"));
        Assert.That(_generatedCode, Does.Contain("_method_getGreeting"));
        Assert.That(_generatedCode, Does.Contain("_method_setValue"));
        Assert.That(_generatedCode, Does.Contain("_method_calculate"));
        Assert.That(_generatedCode, Does.Contain("_method_clone"));
    }

    [Test]
    public void GeneratedCode_SampleClass_HasCustomNamedMethod()
    {
        Assert.That(_generatedCode, Does.Contain("case \"customName\":"));
    }

    [Test]
    public void GeneratedCode_SampleClass_DoesNotHaveHiddenMethod()
    {
        // The hidden method should not be exposed
        Assert.That(_generatedCode, Does.Not.Contain("_method_hiddenMethod"));
        Assert.That(_generatedCode, Does.Not.Contain("case \"hiddenMethod\":"));
    }

    [Test]
    public void GeneratedCode_Vec2_HasAllOperators()
    {
        // Check for Vec2 (SampleStruct) operators
        Assert.That(_generatedCode, Does.Contain("__add"));
        Assert.That(_generatedCode, Does.Contain("__sub"));
        Assert.That(_generatedCode, Does.Contain("__mul"));
        Assert.That(_generatedCode, Does.Contain("__div"));
        Assert.That(_generatedCode, Does.Contain("__unm"));
        Assert.That(_generatedCode, Does.Contain("__eq"));
    }

    [Test]
    public void GeneratedCode_Vec2_HasStaticProperties()
    {
        Assert.That(_generatedCode, Does.Contain("case \"zero\":"));
        Assert.That(_generatedCode, Does.Contain("case \"one\":"));
        Assert.That(_generatedCode, Does.Contain("case \"unitX\":"));
        Assert.That(_generatedCode, Does.Contain("case \"unitY\":"));
    }

    [Test]
    public void GeneratedCode_Vec2_HasInstanceProperties()
    {
        Assert.That(_generatedCode, Does.Contain("case \"length\":"));
        Assert.That(_generatedCode, Does.Contain("case \"lengthSquared\":"));
    }

    [Test]
    public void GeneratedCode_Vec2_HasFields()
    {
        // X and Y should be exposed as fields in lowercase
        Assert.That(_generatedCode, Does.Contain("case \"x\":"));
        Assert.That(_generatedCode, Does.Contain("case \"y\":"));
    }

    [Test]
    public void GeneratedCode_Vec2_HasStaticMethods()
    {
        Assert.That(_generatedCode, Does.Contain("_static_distance"));
        Assert.That(_generatedCode, Does.Contain("_static_fromAngle"));
        Assert.That(_generatedCode, Does.Contain("_static_dot"));
    }

    [Test]
    public void GeneratedCode_Vec2_HasInstanceMethods()
    {
        Assert.That(_generatedCode, Does.Contain("_method_normalized"));
        Assert.That(_generatedCode, Does.Contain("_method_scale"));
        Assert.That(_generatedCode, Does.Contain("_method_set"));
    }

    [Test]
    public void GeneratedCode_Vec3_HasCrossProduct()
    {
        Assert.That(_generatedCode, Does.Contain("_static_cross"));
    }

    [Test]
    public void GeneratedCode_Vec3_HasCrossTypeMethod()
    {
        // ToVec2 returns a SampleStruct
        Assert.That(_generatedCode, Does.Contain("_method_toVec2"));

        // FromVec2 takes a SampleStruct parameter
        Assert.That(_generatedCode, Does.Contain("_static_fromVec2"));
    }

    [Test]
    public void GeneratedCode_UsesUpdateStructForStructMutation()
    {
        // When mutating a struct field or calling a method, UpdateStruct should be called
        Assert.That(_generatedCode, Does.Contain("UpdateStruct(L, 1, obj)"));
    }

    [Test]
    public void GeneratedCode_UsesGetStructFromStackForStructs()
    {
        Assert.That(_generatedCode, Does.Contain("GetStructFromStack<NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleStruct>"));
    }

    [Test]
    public void GeneratedCode_UsesGetObjectFromStackForClasses()
    {
        Assert.That(_generatedCode, Does.Contain("GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass>"));
    }

    [Test]
    public void GeneratedCode_KeepsDelegatesAlive()
    {
        // All CFunction delegates should use KeepAlive to prevent GC
        // The _delegates list is in LuaBindingsBase.cs, but KeepAlive calls are in generated code
        Assert.That(_generatedCode, Does.Contain("KeepAlive("));
        // Storage is now in LuaBindingsBase.cs
        Assert.That(_generatedCode, Does.Not.Contain("private static readonly List<lua_CFunction> _delegates"));
    }

    [Test]
    public void GeneratedCode_SetsGlobalCorrectly()
    {
        // Types should be set as globals with their Lua names
        Assert.That(_generatedCode, Does.Contain("lua_setglobal(L, \"SampleClass\")"));
        Assert.That(_generatedCode, Does.Contain("lua_setglobal(L, \"Vec2\")")); // Custom name
        Assert.That(_generatedCode, Does.Contain("lua_setglobal(L, \"Vec3\")")); // Custom name
    }

    [Test]
    public void GeneratedCode_HandlesNullableStrings()
    {
        // ToObject is now in LuaBindingsBase.cs, so we just verify generated code uses it
        Assert.That(_generatedCode, Does.Contain("ToObject(L,"));
    }

    [Test]
    public void GeneratedCode_HasErrorHandling()
    {
        Assert.That(_generatedCode, Does.Contain("luaL_error"));
    }

    [Test]
    public void GeneratedCode_HasProperMethodDispatch()
    {
        // Methods should check argument count for overload resolution
        Assert.That(_generatedCode, Does.Contain("var argCount = lua_gettop(L)"));
        Assert.That(_generatedCode, Does.Contain("if (argCount =="));
    }

    [Test]
    public void GeneratedCode_CanWriteToFile()
    {
        // Verify we can actually write the generated code to a file
        var tempPath = Path.GetTempFileName();
        try
        {
            File.WriteAllText(tempPath, _generatedCode);
            var readBack = File.ReadAllText(tempPath);
            Assert.That(readBack, Is.EqualTo(_generatedCode));
        }
        finally
        {
            if (File.Exists(tempPath))
            {
                File.Delete(tempPath);
            }
        }
    }
}
