// <auto-generated />
// This file is auto-generated by NFMWorld.LuaSourceGenerator.
// ReSharper disable All
#nullable enable

using LuaNET.LuaJIT;
using static LuaNET.LuaJIT.Lua;
using NFMWorld.LuaSourceGenerator.Test.TestBindings;

namespace NFMWorld.LuaSourceGenerator.Test.TestBindings;

public partial class LuaBindings
{
    // =========== Bindings for IEnumerator`1 (IEnumerator_ReferencedType) ===========
    private static void Register_IEnumerator_ReferencedType(lua_State L)
    {
        RegisterMetatable<System.Collections.Generic.IEnumerator<NFMWorld.LuaSourceGenerator.Test.SampleTypes.ReferencedType>>("MT_IEnumerator_ReferencedType");

        // Create metatable for instances
        luaL_newmetatable(L, "MT_IEnumerator_ReferencedType");

        // __gc metamethod
        lua_pushcfunction(L, KeepAlive(IEnumerator_ReferencedType__gc));
        lua_setfield(L, -2, "__gc");

        // __index metamethod
        lua_pushcfunction(L, KeepAlive(IEnumerator_ReferencedType__index));
        lua_setfield(L, -2, "__index");

        // __newindex metamethod
        lua_pushcfunction(L, KeepAlive(IEnumerator_ReferencedType__newindex));
        lua_setfield(L, -2, "__newindex");

        // __tostring metamethod
        lua_pushcfunction(L, KeepAlive(IEnumerator_ReferencedType__tostring));
        lua_setfield(L, -2, "__tostring");

        lua_pop(L, 1);

        // Create type table for IEnumerator_ReferencedType
        lua_newtable(L);

        // Constructor: new()
        lua_pushcfunction(L, KeepAlive(IEnumerator_ReferencedType_new));
        lua_setfield(L, -2, "new");

        lua_setglobal(L, "IEnumerator_ReferencedType");
    }

    private static int IEnumerator_ReferencedType__gc(lua_State L)
    {
        var ptr = lua_touserdata(L, 1);
        if (ptr != 0)
        {
            unsafe
            {
                var id = *(int*)ptr;
                RemoveObject<System.Collections.Generic.IEnumerator<NFMWorld.LuaSourceGenerator.Test.SampleTypes.ReferencedType>>(id);
            }
        }
        return 0;
    }

    private static int IEnumerator_ReferencedType__index(lua_State L)
    {
        var key = lua_tostring(L, 2);
        if (key == null) { lua_pushnil(L); return 1; }

        var obj = GetObjectFromStack<System.Collections.Generic.IEnumerator<NFMWorld.LuaSourceGenerator.Test.SampleTypes.ReferencedType>>(L, 1);
        if (obj == null) { lua_pushnil(L); return 1; }

        switch (key)
        {
            case "current":
                PushValue(L, obj.Current);
                return 1;
            default:
                lua_pushnil(L);
                return 1;
        }
    }

    private static int IEnumerator_ReferencedType__newindex(lua_State L)
    {
        var key = lua_tostring(L, 2);
        if (key == null) return 0;

        var obj = GetObjectFromStack<System.Collections.Generic.IEnumerator<NFMWorld.LuaSourceGenerator.Test.SampleTypes.ReferencedType>>(L, 1);
        if (obj == null) return 0;

        switch (key)
        {
        }
        return 0;
    }

    private static int IEnumerator_ReferencedType__tostring(lua_State L)
    {
        var obj = GetObjectFromStack<System.Collections.Generic.IEnumerator<NFMWorld.LuaSourceGenerator.Test.SampleTypes.ReferencedType>>(L, 1);
        lua_pushstring(L, obj?.ToString() ?? "nil");
        return 1;
    }

    private static int IEnumerator_ReferencedType_new(lua_State L)
    {
        var argCount = lua_gettop(L);

        luaL_error(L, "Invalid arguments for IEnumerator`1 constructor");
        return 0;
    }

}
