namespace NFMWorld.LuaSourceGenerator;

internal class LuaBindingTypeGenerator(LuaVisibleType type, DiscoveredKind kind, string @namespace)
{
    public bool HasAnythingToGenerate()
    {
        var doesRequireInstanceMethodsForInheritance
            = type.IsVisibleToLua || (kind & (DiscoveredKind.BaseType | DiscoveredKind.Interface)) != 0;

        if (doesRequireInstanceMethodsForInheritance)
        {
            if (type.DeclaredInstanceMethods.Length != 0)
                return true;

            if (type.Operators.Length != 0)
                return true;
        }

        if (type.IsVisibleToLua)
        {
            if (type.StaticMethods.Length != 0)
                return true;
        }

        return false;
    }
    
    public string GenerateCode()
    {
        var sb = new IndentedStringBuilder();

        sb.AppendLine(
            $"""
            // <auto-generated />
            // This file is auto-generated by NFMWorld.LuaSourceGenerator.
            // ReSharper disable All
            #nullable enable

            using System.Runtime.CompilerServices;
            using System.Runtime.InteropServices;
            using LuaJIT;
            using static LuaJIT.Methods;

            namespace {@namespace};

            public unsafe partial class LuaBindings
            """);

        // Determine if we need instance method binding implementations for inheritance
        var doesRequireInstanceMethodsForInheritance
            = type.IsVisibleToLua || (kind & (DiscoveredKind.BaseType | DiscoveredKind.Interface)) != 0;

        using (sb.Block())
        {
            sb.AppendLine($"// =========== Bindings for {type.FullName} ({type.LuaName}) ===========");
            
            sb.AppendLine("#region Instance Methods");
            
            // Instance Methods & Operators: only if visible to Lua
            if (type.IsVisibleToLua)
            {
                if (type.InstanceMethods.Length > 0)
                {
                    sb.AppendLine($"private static readonly luaL_RegManaged[] {type.LuaName}_instance_methods = new luaL_RegManaged[]");

                    using (sb.Block(end: "};"))
                    {
                        foreach (var group in type.InstanceMethods.GroupBy(method => method.LuaName))
                        {
                            sb.AppendLine(
                                $$"""new() { name = "{{group.Key}}", func = &{{group.First().BindingName}} },""");
                        }
                    }
                }

                if (type.Operators.Length > 0)
                {
                    sb.AppendLine($"private static readonly luaL_RegManaged[] {type.LuaName}_operators = new luaL_RegManaged[]");

                    using (sb.Block(end: "};"))
                    {
                        foreach (var group in type.Operators.GroupBy(method => method.LuaName))
                        {
                            sb.AppendLine(
                                $$"""new() { name = "{{group.Key.GetLuaMetamethodName()}}", func = &{{group.First().BindingName}} },""");
                        }
                    }
                }
            }
            
            // Instance Method & Operator Implementations: only if visible to Lua or required for inheritance
            if (doesRequireInstanceMethodsForInheritance)
            {
                sb.AppendLine();
                foreach (var group in type.DeclaredInstanceMethods.GroupBy(method => method.Name))
                {
                    var methodGenerator = new LuaBindingMethodGenerator(type, group.ToArray(), false, 0);
                    sb.AppendLine(methodGenerator.GenerateCode());
                    sb.AppendLine();
                }
                
                foreach (var group in type.Operators.GroupBy(method => method.Name))
                {
                    var methodGenerator = new LuaBindingMethodGenerator(type, group.ToArray(), false, 0);
                    sb.AppendLine(methodGenerator.GenerateCode());
                    sb.AppendLine();
                }
            }
            
            sb.AppendLine("#endregion");
            sb.AppendLine();
            
            // Static Methods
            if (type.IsVisibleToLua)
            {
                if (type.StaticMethods.Length > 0)
                {
                    sb.AppendLine("#region Static Methods");
                    sb.AppendLine($"private static readonly luaL_RegManaged[] {type.LuaName}_static_methods = new luaL_RegManaged[]");

                    using (sb.Block(end: "};"))
                    {
                        foreach (var group in type.StaticMethods.GroupBy(method => method.LuaName))
                        {
                            sb.AppendLine(
                                $$"""new() { name = "{{group.Key}}", func = &{{group.First().BindingName}} },""");
                        }
                    }

                    foreach (var group in type.StaticMethods.GroupBy(method => method.Name))
                    {
                        var methodGenerator = new LuaBindingMethodGenerator(type, group.ToArray(), true, 0);
                        sb.AppendLine(methodGenerator.GenerateCode());
                        sb.AppendLine();
                    }
                    sb.AppendLine("#endregion");
                }
            }
        }
        
        return sb.ToString();
    }

    public string GenerateInitializeCode()
    {
        var sb = new IndentedStringBuilder();
        sb.AppendLine("Register(");
        using (sb.Indent())
        {
            sb.AppendLine("L,");
            sb.AppendLine($"\"{type.LuaName}\",");
            sb.AppendLine($"\"{type.MetatableName}\",");

            if (type.IsVisibleToLua && type.InstanceMethods.Length > 0)
            {
                sb.AppendLine($"{type.LuaName}_instance_methods,");
            }
            else
            {
                sb.AppendLine("null,");
            }

            if (type.IsVisibleToLua && type.Operators.Length > 0)
            {
                sb.AppendLine($"{type.LuaName}_operators,");
            }
            else
            {
                sb.AppendLine("null,");
            }

            if (type.IsVisibleToLua && type.StaticMethods.Length > 0)
            {
                sb.AppendLine($"{type.LuaName}_static_methods,");
            }
            else
            {
                sb.AppendLine("null,");
            }
                    
            // instanceFieldsIndex (todo)
            sb.AppendLine("null,");
                    
            // staticFieldsIndex (todo)
            sb.AppendLine("null");
        }

        sb.AppendLine(");");
        return sb.ToString();
    }

    public bool HasInitializeCode()
    {
        return type.IsVisibleToLua && HasAnythingToGenerate();
    }
}