// <auto-generated />
// This file is auto-generated by NFMWorld.LuaSourceGenerator.
// ReSharper disable All
#nullable enable

using LuaNET.LuaJIT;
using static LuaNET.LuaJIT.Lua;
using NFMWorld.LuaSourceGenerator.Test.TestBindings;

namespace NFMWorld.LuaSourceGenerator.Test.TestBindings;

public partial class LuaBindings
{
    /// <summary>
    /// Initialize all Lua bindings for types marked with [LuaVisible]
    /// </summary>
    public static void Initialize(lua_State L)
    {
        Register_TypeWithArrays(L);
        Register_SampleClass(L);
        Register_SampleStruct(L);
        Register_TypeWithReferences(L);
        Register_Vector3Struct(L);
        Register_ReferencedType(L);
        Register_List_Int32(L);
        Register_List_ReferencedType(L);
        Register_IEnumerable_Int32(L);
        Register_ReadOnlyCollection_Int32(L);
        Register_IComparer_Int32(L);
        Register_IEnumerable_ReferencedType(L);
        Register_ReadOnlyCollection_ReferencedType(L);
        Register_IComparer_ReferencedType(L);
        Register_IEnumerator_Int32(L);
        Register_IList_Int32(L);
        Register_IEnumerator_ReferencedType(L);
        Register_IList_ReferencedType(L);
    }

}
