namespace NFMWorld.LuaSourceGenerator;

internal class LuaBindingTypeGenerator(LuaVisibleType type, DiscoveredKind kind, string @namespace)
{
    public bool HasAnythingToGenerate()
    {
        var doesRequireInstanceMethodsForInheritance
            = type.IsVisibleToLua || (kind & (DiscoveredKind.BaseType | DiscoveredKind.Interface)) != 0;

        if (doesRequireInstanceMethodsForInheritance)
        {
            if (type.DeclaredInstanceMethods.Length != 0)
                return true;

            if (type.Operators.Length != 0)
                return true;
        }

        if (type.IsVisibleToLua)
        {
            if (type.StaticMethods.Length != 0)
                return true;
        }

        return false;
    }
    
    public string GenerateCode()
    {
        var sb = new IndentedStringBuilder();

        sb.AppendLine(
            $"""
            // <auto-generated />
            // This file is auto-generated by NFMWorld.LuaSourceGenerator.
            // ReSharper disable All
            #nullable enable

            using System.Runtime.CompilerServices;
            using System.Runtime.InteropServices;
            using LuaJIT;
            using static LuaJIT.Methods;

            namespace {@namespace};

            public unsafe partial class LuaBindings
            """);

        // Determine if we need instance method binding implementations for inheritance
        var doesRequireInstanceMethodsForInheritance
            = type.IsVisibleToLua || (kind & (DiscoveredKind.BaseType | DiscoveredKind.Interface)) != 0;

        using (sb.Block())
        {
            sb.AppendLine($"// =========== Bindings for {type.FullName} ({type.LuaName}) ===========");
            
            sb.AppendLine("#region Instance Methods");
            
            // Instance Methods & Operators: only if visible to Lua
            if (type.IsVisibleToLua)
            {
                if (type.InstanceMethods.Length > 0)
                {
                    sb.AppendLine($"private static readonly luaL_RegManaged[] {type.LuaName}_instance_methods = new luaL_RegManaged[]");

                    using (sb.Block(end: "};"))
                    {
                        foreach (var group in type.InstanceMethods.GroupBy(method => method.LuaName))
                        {
                            sb.AppendLine(
                                $$"""new() { name = "{{group.Key}}", func = &{{group.First().BindingName}} },""");
                        }
                    }
                }

                if (type.Operators.Length > 0)
                {
                    sb.AppendLine($"private static readonly luaL_RegManaged[] {type.LuaName}_operators = new luaL_RegManaged[]");

                    using (sb.Block(end: "};"))
                    {
                        foreach (var group in type.Operators.GroupBy(method => method.LuaName))
                        {
                            sb.AppendLine(
                                $$"""new() { name = "{{group.Key.GetLuaMetamethodName()}}", func = &{{group.First().BindingName}} },""");
                        }
                    }
                }
            }
            
            // Instance Method & Operator Implementations: only if visible to Lua or required for inheritance
            if (doesRequireInstanceMethodsForInheritance)
            {
                sb.AppendLine();
                foreach (var group in type.DeclaredInstanceMethods.GroupBy(method => method.Name))
                {
                    var methodGenerator = new LuaBindingMethodGenerator(type, group.ToArray(), false, 0);
                    sb.AppendLine(methodGenerator.GenerateCode());
                    sb.AppendLine();
                }
                
                sb.AppendLine();
                foreach (var group in type.Operators.GroupBy(method => method.Name))
                {
                    var methodGenerator = new LuaBindingMethodGenerator(type, group.ToArray(), true, 0);
                    sb.AppendLine(methodGenerator.GenerateCode());
                    sb.AppendLine();
                }
            }
            
            sb.AppendLine("#endregion");
            sb.AppendLine();
            
            // Static Methods
            if (type.IsVisibleToLua)
            {
                if (type.StaticMethods.Length > 0 || type.Constructors.Length > 0 || type.IsStruct)
                {
                    sb.AppendLine("#region Static Methods");
                    sb.AppendLine($"private static readonly luaL_RegManaged[] {type.LuaName}_static_methods = new luaL_RegManaged[]");

                    using (sb.Block(end: "};"))
                    {
                        foreach (var group in type.StaticMethods.GroupBy(method => method.LuaName))
                        {
                            sb.AppendLine(
                                $$"""new() { name = "{{group.Key}}", func = &{{group.First().BindingName}} },""");
                        }

                        if (type.Constructors.Length > 0)
                        {
                            sb.AppendLine(
                                $$"""new() { name = "new", func = &{{type.Constructors[0].BindingName}} },""");
                        }
                        else if (type.IsStruct)
                        {
                            sb.AppendLine(
                                $$"""new() { name = "new", func = &{{type.Type.GetGenericTypeLuaName()}}_struct_new },""");
                        }
                    }

                    foreach (var group in type.StaticMethods.GroupBy(method => method.Name))
                    {
                        var methodGenerator = new LuaBindingMethodGenerator(type, group.ToArray(), true, 0);
                        sb.AppendLine(methodGenerator.GenerateCode());
                        sb.AppendLine();
                    }

                    if (type.Constructors.Length > 0)
                    {
                        sb.AppendLine();
                        var methodGenerator = new LuaBindingMethodGenerator(type, type.Constructors.ToArray(), true, 0);
                        sb.AppendLine(methodGenerator.GenerateCode());
                        sb.AppendLine();
                    } else if (type.IsStruct)
                    {
                        sb.AppendLine(
                            $$"""
                              [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
                              private static int {{type.Type.GetGenericTypeLuaName()}}_struct_new(lua_State L)
                              {
                                  string? errorMsg = null;
                                  try
                                  {
                                      var argCount = lua_gettop(L);
                              
                                      var result = new {{type.Type.GetFullTypeName()}}();
                                      PushValue(L, result);
                                      return 1;
                                  }
                                  catch (System.Exception ex)
                                  {
                                      errorMsg = FormatException(ex);
                                  }
                                  if (errorMsg != null)
                                  {
                                      return luaL_error(L, errorMsg);
                                  }
                                  return Unreachable();
                              }
                              """);
                    }
                    
                    sb.AppendLine("#endregion");
                }
            }
            
            // Instance Fields & Properties
            if (type.IsVisibleToLua && (type.InstanceFields.Length > 0 || type.InstanceProperties.Length > 0 || type.InstanceIndexer != null))
            {
                var indexGenerator = new LuaBindingIndexGenerator(type, type.InstanceFields, type.InstanceProperties, type.InstanceIndexer, false);
                sb.AppendLine(indexGenerator.GenerateCode());
                sb.AppendLine();
            }
            
            // Static Fields & Properties
            if (type.IsVisibleToLua && (type.StaticFields.Length > 0 || type.StaticProperties.Length > 0 || type.StaticIndexer != null))
            {
                var indexGenerator = new LuaBindingIndexGenerator(type, type.StaticFields, type.StaticProperties, type.StaticIndexer, true);
                sb.AppendLine(indexGenerator.GenerateCode());
                sb.AppendLine();
            }
        }
        
        return sb.ToString();
    }

    public string GenerateInitializeCode()
    {
        var sb = new IndentedStringBuilder();
        sb.AppendLine($"Register(");
        using (sb.Indent())
        {
            sb.AppendLine("L,");
            sb.AppendLine($"\"{type.LuaName}\",");
            sb.AppendLine($"\"{type.MetatableName}\",");

            if (type.IsVisibleToLua && (type.InstanceMethods.Length > 0 || type.Operators.Length > 0))
            {
                sb.AppendLine($"{type.LuaName}_instance_metamethods,");
            }
            else
            {
                sb.AppendLine("null,");
            }

            if (type.IsVisibleToLua && type.StaticMethods.Length > 0)
            {
                sb.AppendLine($"{type.LuaName}_static_methods,");
            }
            else
            {
                sb.AppendLine("null,");
            }

            if (type.IsVisibleToLua && (type.StaticFields.Length > 0 || type.StaticProperties.Length > 0 || type.StaticIndexer != null))
            {
                sb.AppendLine($"{type.LuaName}_static_metamethods");
            }
            else
            {
                sb.AppendLine("null");
            }
        }

        sb.AppendLine(");");

        if (type.IsVisibleToLua && !type.Type.IsStaticClass())
        {
            sb.AppendLine($"RegisterMetatable<{type.Type.GetFullTypeName()}>(\"{type.MetatableName}\");");
        }
        
        return sb.ToString();
    }

    public bool HasInitializeCode()
    {
        return type.IsVisibleToLua && HasAnythingToGenerate();
    }
}