// Lua Source Generator
// This program uses reflection to find all types marked with [LuaVisible]
// and generates Lua binding code for them.

using System.Reflection;
using System.Text;
using Maxine.Extensions;
using nfm_world_library;
using nfm_world_library.Lua;

namespace NFMWorld.LuaSourceGenerator;

public static class Program
{
    public static void Main(string[] args)
    {
        if (args.Length != 2)
        {
            Console.WriteLine("Usage: NFMWorld.LuaSourceGenerator <input-assembly-path> <output-file-path>");

            args =
            [
                typeof(BackendGameSparker).Assembly.Location,
                Path.Combine(ProjectUtils.TryGetSolutionDirectory() ?? "", "NFMWorld.Library", "Lua", "Lua.Generated.cs"),
            ];
        }

        var inputAssemblyPath = args[0];
        var outputFilePath = args[1];
        var @namespace = args.Length >= 3 ? args[2] : "nfm_world_library.Lua";

        var assembly = Assembly.LoadFrom(inputAssemblyPath);
        var generator = new LuaBindingGenerator(assembly, @namespace);
        var generatedCode = generator.Generate();

        File.WriteAllText(outputFilePath, generatedCode);
        Console.WriteLine($"Generated Lua bindings written to {outputFilePath}");
    }
}

/// <summary>
/// Generator that creates Lua bindings for the test sample types.
/// </summary>
public class LuaBindingGenerator(Assembly assembly, string @namespace)
{
    private readonly StringBuilder _sb = new();
    private int _indent;

    private void AppendLine(string line = "")
    {
        if (string.IsNullOrEmpty(line))
        {
            _sb.AppendLine();
        }
        else
        {
            _sb.Append(new string(' ', _indent * 4));
            _sb.AppendLine(line);
        }
    }

    private IDisposable Indent()
    {
        _indent++;
        return new IndentDisposable(this);
    }

    private class IndentDisposable : IDisposable
    {
        private readonly LuaBindingGenerator _gen;
        public IndentDisposable(LuaBindingGenerator gen) => _gen = gen;
        public void Dispose() => _gen._indent--;
    }

    /// <summary>
    /// Generate bindings for all sample types in the test project.
    /// </summary>
    public string Generate()
    {
        // Find all types with [LuaVisible] in the test assembly
        var types = new List<TypeInfo>();

        foreach (var type in assembly.GetTypes())
        {
            if (type.GetCustomAttribute<LuaVisibleAttribute>() is { } attr)
            {
                types.Add(new TypeInfo(type, attr));
            }
        }

        GenerateCode(types);
        return _sb.ToString();
    }

    private void GenerateCode(List<TypeInfo> types)
    {
        AppendLine("// <auto-generated />");
        AppendLine("// This file is auto-generated by GenerateTestBindings.");
        AppendLine("// Run the RegenerateBindings test to update this file.");
        AppendLine("// The base infrastructure (helper methods, storage, etc.) is in LuaBindingsBase.cs");
        AppendLine("// ReSharper disable All");
        AppendLine("#nullable enable");
        AppendLine();
        AppendLine("using LuaNET.LuaJIT;");
        AppendLine("using static LuaNET.LuaJIT.Lua;");
        AppendLine();
        AppendLine($"namespace {@namespace};");
        AppendLine();
        AppendLine("public partial class LuaBindings");
        AppendLine("{");

        using (Indent())
        {
            GenerateInitializeMethod(types);

            foreach (var typeInfo in types)
            {
                GenerateTypeBindings(typeInfo);
            }
        }

        AppendLine("}");
    }

    private void GenerateInitializeMethod(List<TypeInfo> types)
    {
        AppendLine("/// <summary>");
        AppendLine("/// Initialize all Lua bindings for types marked with [LuaVisible]");
        AppendLine("/// </summary>");
        AppendLine("public static void Initialize(lua_State L)");
        AppendLine("{");
        using (Indent())
        {
            foreach (var typeInfo in types)
            {
                AppendLine($"Register_{GetSafeTypeName(typeInfo.Type)}(L);");
            }
        }
        AppendLine("}");
        AppendLine();
    }

    private void GenerateTypeBindings(TypeInfo typeInfo)
    {
        var type = typeInfo.Type;
        var luaName = typeInfo.LuaName;
        var safeName = GetSafeTypeName(type);
        var metatableName = $"MT_{safeName}";
        var isStruct = type.IsValueType;
        var fullTypeName = GetFullTypeName(type);

        AppendLine($"// =========== Bindings for {type.Name} ({luaName}) ===========");
        AppendLine($"private static void Register_{safeName}(lua_State L)");
        AppendLine("{");
        using (Indent())
        {
            AppendLine($"RegisterMetatable<{fullTypeName}>(\"{metatableName}\");");
            AppendLine();
            AppendLine("// Create metatable for instances");
            AppendLine($"luaL_newmetatable(L, \"{metatableName}\");");
            AppendLine();

            // __gc
            AppendLine("// __gc metamethod");
            AppendLine($"lua_pushcfunction(L, KeepAlive({safeName}__gc));");
            AppendLine("lua_setfield(L, -2, \"__gc\");");
            AppendLine();

            // __index
            AppendLine("// __index metamethod");
            AppendLine($"lua_pushcfunction(L, KeepAlive({safeName}__index));");
            AppendLine("lua_setfield(L, -2, \"__index\");");
            AppendLine();

            // __newindex
            AppendLine("// __newindex metamethod");
            AppendLine($"lua_pushcfunction(L, KeepAlive({safeName}__newindex));");
            AppendLine("lua_setfield(L, -2, \"__newindex\");");
            AppendLine();

            // Operator metamethods
            GenerateOperatorMetamethods(type, safeName);

            // __tostring
            AppendLine("// __tostring metamethod");
            AppendLine($"lua_pushcfunction(L, KeepAlive({safeName}__tostring));");
            AppendLine("lua_setfield(L, -2, \"__tostring\");");
            AppendLine();

            AppendLine("lua_pop(L, 1);");
            AppendLine();

            // Type table
            AppendLine($"// Create type table for {luaName}");
            AppendLine("lua_newtable(L);");
            AppendLine();

            // Constructor
            AppendLine("// Constructor: new()");
            AppendLine($"lua_pushcfunction(L, KeepAlive({safeName}_new));");
            AppendLine("lua_setfield(L, -2, \"new\");");
            AppendLine();

            // Static methods
            var staticMethods = type.GetMethods(BindingFlags.Public | BindingFlags.Static)
                .Where(m => !m.IsSpecialName && m.GetCustomAttribute<LuaHiddenAttribute>() == null)
                .GroupBy(m => GetLuaMethodName(m))
                .ToList();

            foreach (var methodGroup in staticMethods)
            {
                var methodName = methodGroup.Key;
                AppendLine($"// Static method: {methodName}");
                AppendLine($"lua_pushcfunction(L, KeepAlive({safeName}_static_{GetSafeMethodName(methodName)}));");
                AppendLine($"lua_setfield(L, -2, \"{methodName}\");");
                AppendLine();
            }

            // Static properties metatable
            var staticProps = type.GetProperties(BindingFlags.Public | BindingFlags.Static)
                .Where(p => p.GetCustomAttribute<LuaHiddenAttribute>() == null)
                .ToList();

            if (staticProps.Count > 0)
            {
                AppendLine("// Create metatable for type table (static properties)");
                AppendLine("lua_newtable(L);");
                AppendLine($"lua_pushcfunction(L, KeepAlive({safeName}_type__index));");
                AppendLine("lua_setfield(L, -2, \"__index\");");

                var writableStaticProps = staticProps.Where(p => p.CanWrite).ToList();
                if (writableStaticProps.Count > 0)
                {
                    AppendLine($"lua_pushcfunction(L, KeepAlive({safeName}_type__newindex));");
                    AppendLine("lua_setfield(L, -2, \"__newindex\");");
                }

                AppendLine("lua_setmetatable(L, -2);");
                AppendLine();
            }

            AppendLine($"lua_setglobal(L, \"{luaName}\");");
        }
        AppendLine("}");
        AppendLine();

        // Generate all method implementations
        GenerateGcMethod(safeName, fullTypeName);
        GenerateIndexMethod(type, safeName, isStruct, fullTypeName);
        GenerateNewIndexMethod(type, safeName, isStruct, fullTypeName);
        GenerateTostringMethod(safeName, isStruct, fullTypeName);
        GenerateOperatorMethods(type, safeName, fullTypeName);
        GenerateConstructorMethod(type, safeName, isStruct, fullTypeName);
        GenerateStaticMethods(type, safeName, fullTypeName);
        GenerateInstanceMethods(type, safeName, isStruct, fullTypeName);

        var staticPropsForAccessors = type.GetProperties(BindingFlags.Public | BindingFlags.Static)
            .Where(p => p.GetCustomAttribute<LuaHiddenAttribute>() == null)
            .ToList();

        if (staticPropsForAccessors.Count > 0)
        {
            GenerateStaticPropertyAccessors(type, safeName, fullTypeName);
        }
    }

    private void GenerateOperatorMetamethods(Type type, string safeName)
    {
        var operators = GetOperatorMethods(type);

        foreach (var op in operators)
        {
            var luaMetamethod = GetLuaMetamethodName(op.Name);
            if (luaMetamethod != null)
            {
                AppendLine($"// Operator: {luaMetamethod}");
                AppendLine($"lua_pushcfunction(L, KeepAlive({safeName}_op_{GetSafeMethodName(op.Name)}));");
                AppendLine($"lua_setfield(L, -2, \"{luaMetamethod}\");");
                AppendLine();
            }
        }
    }

    private void GenerateGcMethod(string safeName, string fullTypeName)
    {
        AppendLine($"private static int {safeName}__gc(lua_State L)");
        AppendLine("{");
        using (Indent())
        {
            AppendLine("var ptr = lua_touserdata(L, 1);");
            AppendLine("if (ptr != 0)");
            AppendLine("{");
            using (Indent())
            {
                AppendLine("unsafe");
                AppendLine("{");
                using (Indent())
                {
                    AppendLine("var id = *(int*)ptr;");
                    AppendLine($"RemoveObject<{fullTypeName}>(id);");
                }
                AppendLine("}");
            }
            AppendLine("}");
            AppendLine("return 0;");
        }
        AppendLine("}");
        AppendLine();
    }

    private void GenerateIndexMethod(Type type, string safeName, bool isStruct, string fullTypeName)
    {
        AppendLine($"private static int {safeName}__index(lua_State L)");
        AppendLine("{");
        using (Indent())
        {
            AppendLine("var key = lua_tostring(L, 2);");
            AppendLine("if (key == null) { lua_pushnil(L); return 1; }");
            AppendLine();

            if (isStruct)
            {
                AppendLine($"var obj = GetStructFromStack<{fullTypeName}>(L, 1);");
            }
            else
            {
                AppendLine($"var obj = GetObjectFromStack<{fullTypeName}>(L, 1);");
                AppendLine("if (obj == null) { lua_pushnil(L); return 1; }");
            }
            AppendLine();

            AppendLine("switch (key)");
            AppendLine("{");
            using (Indent())
            {
                // Properties
                var props = type.GetProperties(BindingFlags.Public | BindingFlags.Instance)
                    .Where(p => p.GetCustomAttribute<LuaHiddenAttribute>() == null && p.CanRead)
                    .ToList();

                foreach (var prop in props)
                {
                    var luaName = GetLuaPropertyName(prop);
                    AppendLine($"case \"{luaName}\":");
                    using (Indent())
                    {
                        GeneratePushValue($"obj.{prop.Name}", prop.PropertyType);
                        AppendLine("return 1;");
                    }
                }

                // Fields
                var fields = type.GetFields(BindingFlags.Public | BindingFlags.Instance)
                    .Where(f => f.GetCustomAttribute<LuaHiddenAttribute>() == null)
                    .ToList();

                foreach (var field in fields)
                {
                    var luaName = GetLuaFieldName(field);
                    AppendLine($"case \"{luaName}\":");
                    using (Indent())
                    {
                        GeneratePushValue($"obj.{field.Name}", field.FieldType);
                        AppendLine("return 1;");
                    }
                }

                // Instance methods
                var methods = type.GetMethods(BindingFlags.Public | BindingFlags.Instance)
                    .Where(m => !m.IsSpecialName && m.GetCustomAttribute<LuaHiddenAttribute>() == null)
                    .GroupBy(m => GetLuaMethodName(m))
                    .ToList();

                foreach (var methodGroup in methods)
                {
                    var methodName = methodGroup.Key;
                    AppendLine($"case \"{methodName}\":");
                    using (Indent())
                    {
                        AppendLine($"lua_pushcfunction(L, KeepAlive({safeName}_method_{GetSafeMethodName(methodName)}));");
                        AppendLine("return 1;");
                    }
                }

                AppendLine("default:");
                using (Indent())
                {
                    AppendLine("lua_pushnil(L);");
                    AppendLine("return 1;");
                }
            }
            AppendLine("}");
        }
        AppendLine("}");
        AppendLine();
    }

    private void GenerateNewIndexMethod(Type type, string safeName, bool isStruct, string fullTypeName)
    {
        AppendLine($"private static int {safeName}__newindex(lua_State L)");
        AppendLine("{");
        using (Indent())
        {
            AppendLine("var key = lua_tostring(L, 2);");
            AppendLine("if (key == null) return 0;");
            AppendLine();

            if (isStruct)
            {
                AppendLine($"var obj = GetStructFromStack<{fullTypeName}>(L, 1);");
            }
            else
            {
                AppendLine($"var obj = GetObjectFromStack<{fullTypeName}>(L, 1);");
                AppendLine("if (obj == null) return 0;");
            }
            AppendLine();

            AppendLine("switch (key)");
            AppendLine("{");
            using (Indent())
            {
                // Writable properties (excluding init-only)
                var props = type.GetProperties(BindingFlags.Public | BindingFlags.Instance)
                    .Where(p => p.GetCustomAttribute<LuaHiddenAttribute>() == null && p.CanWrite && !IsInitOnly(p))
                    .ToList();

                foreach (var prop in props)
                {
                    var luaName = GetLuaPropertyName(prop);
                    AppendLine($"case \"{luaName}\":");
                    using (Indent())
                    {
                        GenerateToObjectCode($"obj.{prop.Name}", prop.PropertyType, "3");
                        if (isStruct) AppendLine("UpdateStruct(L, 1, obj);");
                        AppendLine("break;");
                    }
                }

                // Writable fields
                var fields = type.GetFields(BindingFlags.Public | BindingFlags.Instance)
                    .Where(f => f.GetCustomAttribute<LuaHiddenAttribute>() == null && !f.IsInitOnly)
                    .ToList();

                foreach (var field in fields)
                {
                    var luaName = GetLuaFieldName(field);
                    AppendLine($"case \"{luaName}\":");
                    using (Indent())
                    {
                        GenerateToObjectCode($"obj.{field.Name}", field.FieldType, "3");
                        if (isStruct) AppendLine("UpdateStruct(L, 1, obj);");
                        AppendLine("break;");
                    }
                }
            }
            AppendLine("}");
            AppendLine("return 0;");
        }
        AppendLine("}");
        AppendLine();
    }

    private void GenerateTostringMethod(string safeName, bool isStruct, string fullTypeName)
    {
        AppendLine($"private static int {safeName}__tostring(lua_State L)");
        AppendLine("{");
        using (Indent())
        {
            if (isStruct)
            {
                AppendLine($"var obj = GetStructFromStack<{fullTypeName}>(L, 1);");
                AppendLine("lua_pushstring(L, obj.ToString() ?? \"\");");
            }
            else
            {
                AppendLine($"var obj = GetObjectFromStack<{fullTypeName}>(L, 1);");
                AppendLine("lua_pushstring(L, obj?.ToString() ?? \"nil\");");
            }
            AppendLine("return 1;");
        }
        AppendLine("}");
        AppendLine();
    }

    private void GenerateOperatorMethods(Type type, string safeName, string fullTypeName)
    {
        var operators = GetOperatorMethods(type);

        foreach (var op in operators)
        {
            var luaMetamethod = GetLuaMetamethodName(op.Name);
            if (luaMetamethod == null) continue;

            AppendLine($"private static int {safeName}_op_{GetSafeMethodName(op.Name)}(lua_State L)");
            AppendLine("{");
            using (Indent())
            {
                var parameters = op.Parameters;

                if (parameters.Length == 2)
                {
                    var leftType = GetFullTypeName(parameters[0].ParameterType);
                    var rightType = GetFullTypeName(parameters[1].ParameterType);
                    AppendLine($"var left = ToObject<{leftType}>(L, 1)!;");
                    AppendLine($"var right = ToObject<{rightType}>(L, 2)!;");

                    // Use the actual operator syntax
                    var opSymbol = GetOperatorSymbol(op.Name);
                    if (opSymbol != null)
                    {
                        if (op.Name == "op_Equality")
                        {
                            AppendLine($"lua_pushboolean(L, left == right ? 1 : 0);");
                        }
                        else
                        {
                            AppendLine($"var result = left {opSymbol} right;");
                            GeneratePushValue("result", op.Method.ReturnType);
                        }
                    }
                    else
                    {
                        AppendLine($"var result = {fullTypeName}.{op.Name}(left, right);");
                        GeneratePushValue("result", op.Method.ReturnType);
                    }
                    AppendLine("return 1;");
                }
                else if (parameters.Length == 1)
                {
                    var operandType = GetFullTypeName(parameters[0].ParameterType);
                    AppendLine($"var operand = ToObject<{operandType}>(L, 1)!;");

                    var opSymbol = GetOperatorSymbol(op.Name);
                    if (opSymbol != null)
                    {
                        AppendLine($"var result = {opSymbol}operand;");
                    }
                    else
                    {
                        AppendLine($"var result = {fullTypeName}.{op.Name}(operand);");
                    }
                    GeneratePushValue("result", op.Method.ReturnType);
                    AppendLine("return 1;");
                }
            }
            AppendLine("}");
            AppendLine();
        }
    }

    private void GenerateConstructorMethod(Type type, string safeName, bool isStruct, string fullTypeName)
    {
        var constructors = type.GetConstructors(BindingFlags.Public | BindingFlags.Instance)
            .Where(c => c.GetCustomAttribute<LuaHiddenAttribute>() == null)
            .OrderBy(c => c.GetParameters().Length)
            .ToList();

        AppendLine($"private static int {safeName}_new(lua_State L)");
        AppendLine("{");
        using (Indent())
        {
            AppendLine("var argCount = lua_gettop(L);");
            AppendLine();

            // Default constructor for structs
            if (isStruct)
            {
                AppendLine("if (argCount == 0)");
                AppendLine("{");
                using (Indent())
                {
                    AppendLine($"var obj = new {fullTypeName}();");
                    AppendLine($"PushObject(L, obj, \"MT_{safeName}\");");
                    AppendLine("return 1;");
                }
                AppendLine("}");
                AppendLine();
            }

            foreach (var ctor in constructors)
            {
                var parameters = ctor.GetParameters();
                if (isStruct && parameters.Length == 0) continue; // Already handled

                AppendLine($"if (argCount == {parameters.Length})");
                AppendLine("{");
                using (Indent())
                {
                    for (int i = 0; i < parameters.Length; i++)
                    {
                        var param = parameters[i];
                        var paramType = GetFullTypeName(param.ParameterType);
                        AppendLine($"var arg{i} = ToObject<{paramType}>(L, {i + 1})!;");
                    }

                    var argList = string.Join(", ", parameters.Select((_, i) => $"arg{i}"));
                    AppendLine($"var obj = new {fullTypeName}({argList});");
                    AppendLine($"PushObject(L, obj, \"MT_{safeName}\");");
                    AppendLine("return 1;");
                }
                AppendLine("}");
                AppendLine();
            }

            AppendLine($"luaL_error(L, \"Invalid arguments for {type.Name} constructor\");");
            AppendLine("return 0;");
        }
        AppendLine("}");
        AppendLine();
    }

    private void GenerateStaticMethods(Type type, string safeName, string fullTypeName)
    {
        var staticMethods = type.GetMethods(BindingFlags.Public | BindingFlags.Static)
            .Where(m => !m.IsSpecialName && m.GetCustomAttribute<LuaHiddenAttribute>() == null)
            .GroupBy(m => GetLuaMethodName(m))
            .ToList();

        foreach (var methodGroup in staticMethods)
        {
            var methodName = methodGroup.Key;
            var overloads = methodGroup.OrderBy(m => m.GetParameters().Length).ToList();

            AppendLine($"private static int {safeName}_static_{GetSafeMethodName(methodName)}(lua_State L)");
            AppendLine("{");
            using (Indent())
            {
                AppendLine("var argCount = lua_gettop(L);");
                AppendLine();

                foreach (var method in overloads)
                {
                    var parameters = method.GetParameters();
                    AppendLine($"if (argCount == {parameters.Length})");
                    AppendLine("{");
                    using (Indent())
                    {
                        for (int i = 0; i < parameters.Length; i++)
                        {
                            var param = parameters[i];
                            var paramType = GetFullTypeName(param.ParameterType);
                            AppendLine($"var arg{i} = ToObject<{paramType}>(L, {i + 1})!;");
                        }

                        var argList = string.Join(", ", parameters.Select((_, i) => $"arg{i}"));

                        if (method.ReturnType == typeof(void))
                        {
                            AppendLine($"{fullTypeName}.{method.Name}({argList});");
                            AppendLine("return 0;");
                        }
                        else
                        {
                            AppendLine($"var result = {fullTypeName}.{method.Name}({argList});");
                            GeneratePushValue("result", method.ReturnType);
                            AppendLine("return 1;");
                        }
                    }
                    AppendLine("}");
                    AppendLine();
                }

                AppendLine($"luaL_error(L, \"Invalid arguments for {methodName}\");");
                AppendLine("return 0;");
            }
            AppendLine("}");
            AppendLine();
        }
    }

    private void GenerateInstanceMethods(Type type, string safeName, bool isStruct, string fullTypeName)
    {
        var methods = type.GetMethods(BindingFlags.Public | BindingFlags.Instance)
            .Where(m => !m.IsSpecialName && m.GetCustomAttribute<LuaHiddenAttribute>() == null)
            .GroupBy(m => GetLuaMethodName(m))
            .ToList();

        foreach (var methodGroup in methods)
        {
            var methodName = methodGroup.Key;
            var overloads = methodGroup.OrderBy(m => m.GetParameters().Length).ToList();

            AppendLine($"private static int {safeName}_method_{GetSafeMethodName(methodName)}(lua_State L)");
            AppendLine("{");
            using (Indent())
            {
                AppendLine("var argCount = lua_gettop(L) - 1; // First arg is self");
                AppendLine();

                if (isStruct)
                {
                    AppendLine($"var self = GetStructFromStack<{fullTypeName}>(L, 1);");
                }
                else
                {
                    AppendLine($"var self = GetObjectFromStack<{fullTypeName}>(L, 1);");
                    AppendLine("if (self == null)");
                    AppendLine("{");
                    using (Indent())
                    {
                        AppendLine($"luaL_error(L, \"Expected {type.Name} as first argument\");");
                        AppendLine("return 0;");
                    }
                    AppendLine("}");
                }
                AppendLine();

                foreach (var method in overloads)
                {
                    var parameters = method.GetParameters();
                    AppendLine($"if (argCount == {parameters.Length})");
                    AppendLine("{");
                    using (Indent())
                    {
                        for (int i = 0; i < parameters.Length; i++)
                        {
                            var param = parameters[i];
                            var paramType = GetFullTypeName(param.ParameterType);
                            AppendLine($"var arg{i} = ToObject<{paramType}>(L, {i + 2})!;");
                        }

                        var argList = string.Join(", ", parameters.Select((_, i) => $"arg{i}"));

                        if (method.ReturnType == typeof(void))
                        {
                            AppendLine($"self.{method.Name}({argList});");
                            if (isStruct) AppendLine("UpdateStruct(L, 1, self);");
                            AppendLine("return 0;");
                        }
                        else
                        {
                            AppendLine($"var result = self.{method.Name}({argList});");
                            if (isStruct) AppendLine("UpdateStruct(L, 1, self);");
                            GeneratePushValue("result", method.ReturnType);
                            AppendLine("return 1;");
                        }
                    }
                    AppendLine("}");
                    AppendLine();
                }

                AppendLine($"luaL_error(L, \"Invalid arguments for {methodName}\");");
                AppendLine("return 0;");
            }
            AppendLine("}");
            AppendLine();
        }
    }

    private void GenerateStaticPropertyAccessors(Type type, string safeName, string fullTypeName)
    {
        var staticProps = type.GetProperties(BindingFlags.Public | BindingFlags.Static)
            .Where(p => p.GetCustomAttribute<LuaHiddenAttribute>() == null)
            .ToList();

        // __index for static properties
        AppendLine($"private static int {safeName}_type__index(lua_State L)");
        AppendLine("{");
        using (Indent())
        {
            AppendLine("var key = lua_tostring(L, 2);");
            AppendLine("if (key == null) { lua_pushnil(L); return 1; }");
            AppendLine();
            AppendLine("switch (key)");
            AppendLine("{");
            using (Indent())
            {
                foreach (var prop in staticProps.Where(p => p.CanRead))
                {
                    var luaName = GetLuaPropertyName(prop);
                    AppendLine($"case \"{luaName}\":");
                    using (Indent())
                    {
                        GeneratePushValue($"{fullTypeName}.{prop.Name}", prop.PropertyType);
                        AppendLine("return 1;");
                    }
                }

                AppendLine("default:");
                using (Indent())
                {
                    AppendLine("lua_rawget(L, 1);");
                    AppendLine("return 1;");
                }
            }
            AppendLine("}");
        }
        AppendLine("}");
        AppendLine();

        // __newindex for static properties (if any writable, excluding init-only)
        var writableProps = staticProps.Where(p => p.CanWrite && !IsInitOnly(p)).ToList();
        if (writableProps.Count > 0)
        {
            AppendLine($"private static int {safeName}_type__newindex(lua_State L)");
            AppendLine("{");
            using (Indent())
            {
                AppendLine("var key = lua_tostring(L, 2);");
                AppendLine("if (key == null) return 0;");
                AppendLine();
                AppendLine("switch (key)");
                AppendLine("{");
                using (Indent())
                {
                    foreach (var prop in writableProps)
                    {
                        var luaName = GetLuaPropertyName(prop);
                        AppendLine($"case \"{luaName}\":");
                        using (Indent())
                        {
                            GenerateToObjectCode($"{fullTypeName}.{prop.Name}", prop.PropertyType, "3");
                            AppendLine("return 0;");
                        }
                    }

                    AppendLine("default:");
                    using (Indent())
                    {
                        AppendLine("lua_rawset(L, 1);");
                        AppendLine("return 0;");
                    }
                }
                AppendLine("}");
            }
            AppendLine("}");
            AppendLine();
        }
    }

    #region Helpers

    private static bool IsInitOnly(PropertyInfo property)
    {
        if (property.SetMethod == null) return false;
        return property.SetMethod.ReturnParameter.GetRequiredCustomModifiers()
            .Any(t => t.Name == "IsExternalInit");
    }

    private static bool IsNullable(Type type)
    {
        return type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Nullable<>);
    }

    private void GeneratePushValue(string valueExpression, Type type)
    {
        if (IsNullable(type))
        {
            AppendLine($"if ({valueExpression}.HasValue)");
            using (Indent())
            {
                AppendLine($"PushValue(L, {valueExpression}.Value);");
            }
            AppendLine("else");
            using (Indent())
            {
                AppendLine("lua_pushnil(L);");
            }
        }
        else
        {
            AppendLine($"PushValue(L, {valueExpression});");
        }
    }

    private void GenerateToObjectCode(string targetExpression, Type type, string luaStackIndex)
    {
        var fullTypeName = GetFullTypeName(type);
        if (IsNullable(type))
        {
            var underlyingType = Nullable.GetUnderlyingType(type)!;
            var underlyingTypeName = GetFullTypeName(underlyingType);
            AppendLine($"if (lua_isnil(L, {luaStackIndex}) != 0)");
            using (Indent())
            {
                AppendLine($"{targetExpression} = null;");
            }
            AppendLine("else");
            using (Indent())
            {
                AppendLine($"{targetExpression} = ToObject<{underlyingTypeName}>(L, {luaStackIndex})!;");
            }
        }
        else
        {
            AppendLine($"{targetExpression} = ToObject<{fullTypeName}>(L, {luaStackIndex})!;");
        }
    }

    private static string GetSafeTypeName(Type type) => type.Name.Replace(".", "_").Replace("+", "_").Replace("`", "_");

    private static string GetFullTypeName(Type type)
    {
        if (type == typeof(int)) return "int";
        if (type == typeof(long)) return "long";
        if (type == typeof(float)) return "float";
        if (type == typeof(double)) return "double";
        if (type == typeof(bool)) return "bool";
        if (type == typeof(string)) return "string";
        if (type == typeof(void)) return "void";
        if (type == typeof(object)) return "object";
        return type.FullName ?? type.Name;
    }

    private static string GetSafeMethodName(string methodName) =>
        methodName.Replace(".", "_").Replace("+", "_").Replace("<", "_").Replace(">", "_");

    private static string GetLuaMethodName(MethodInfo method)
    {
        var attr = method.GetCustomAttribute<LuaNameAttribute>();
        return attr?.Name ?? ToCamelCase(method.Name);
    }

    private static string GetLuaPropertyName(PropertyInfo prop)
    {
        var attr = prop.GetCustomAttribute<LuaNameAttribute>();
        return attr?.Name ?? ToCamelCase(prop.Name);
    }

    private static string GetLuaFieldName(FieldInfo field)
    {
        var attr = field.GetCustomAttribute<LuaNameAttribute>();
        return attr?.Name ?? ToCamelCase(field.Name.TrimStart('_'));
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        return char.ToLowerInvariant(name[0]) + name[1..];
    }

    private static List<OperatorInfo> GetOperatorMethods(Type type)
    {
        var operators = new List<OperatorInfo>();
        var methods = type.GetMethods(BindingFlags.Public | BindingFlags.Static)
            .Where(m => m.IsSpecialName && m.Name.StartsWith("op_"));

        foreach (var method in methods)
        {
            operators.Add(new OperatorInfo(method.Name, method.GetParameters(), method));
        }

        return operators;
    }

    private static string? GetLuaMetamethodName(string operatorName) => operatorName switch
    {
        "op_Addition" => "__add",
        "op_Subtraction" => "__sub",
        "op_Multiply" => "__mul",
        "op_Division" => "__div",
        "op_Modulus" => "__mod",
        "op_UnaryNegation" => "__unm",
        "op_Equality" => "__eq",
        "op_LessThan" => "__lt",
        "op_LessThanOrEqual" => "__le",
        _ => null
    };

    private static string? GetOperatorSymbol(string operatorName) => operatorName switch
    {
        "op_Addition" => "+",
        "op_Subtraction" => "-",
        "op_Multiply" => "*",
        "op_Division" => "/",
        "op_Modulus" => "%",
        "op_UnaryNegation" => "-",
        "op_Equality" => "==",
        _ => null
    };

    #endregion
}

public record TypeInfo(Type Type, LuaVisibleAttribute Attribute)
{
    public string LuaName => Attribute.Name ?? Type.Name;
}

public record OperatorInfo(string Name, ParameterInfo[] Parameters, MethodInfo Method);
