// <auto-generated />
// This file is auto-generated by NFMWorld.LuaSourceGenerator.
// ReSharper disable All
#nullable enable

using LuaNET.LuaJIT;
using static LuaNET.LuaJIT.Lua;
using NFMWorld.LuaSourceGenerator.Test.TestBindings;

namespace NFMWorld.LuaSourceGenerator.Test.TestBindings;

public partial class LuaBindings
{
    // =========== Bindings for SampleClass (SampleClass) ===========
    private static void Register_SampleClass(lua_State L)
    {
        RegisterMetatable<NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass>("MT_SampleClass");

        // Create metatable for instances
        luaL_newmetatable(L, "MT_SampleClass");

        // __gc metamethod
        lua_pushcfunction(L, KeepAlive(SampleClass__gc));
        lua_setfield(L, -2, "__gc");

        // __index metamethod
        lua_pushcfunction(L, KeepAlive(SampleClass__index));
        lua_setfield(L, -2, "__index");

        // __newindex metamethod
        lua_pushcfunction(L, KeepAlive(SampleClass__newindex));
        lua_setfield(L, -2, "__newindex");

        // __tostring metamethod
        lua_pushcfunction(L, KeepAlive(SampleClass__tostring));
        lua_setfield(L, -2, "__tostring");

        lua_pop(L, 1);

        // Create type table for SampleClass
        lua_newtable(L);

        // Constructor: new()
        lua_pushcfunction(L, KeepAlive(SampleClass_new));
        lua_setfield(L, -2, "new");

        // Static method: add
        lua_pushcfunction(L, KeepAlive(SampleClass_static_add));
        lua_setfield(L, -2, "add");

        // Static method: concat
        lua_pushcfunction(L, KeepAlive(SampleClass_static_concat));
        lua_setfield(L, -2, "concat");

        // Static method: incrementCounter
        lua_pushcfunction(L, KeepAlive(SampleClass_static_incrementCounter));
        lua_setfield(L, -2, "incrementCounter");

        // Static method: addNullable
        lua_pushcfunction(L, KeepAlive(SampleClass_static_addNullable));
        lua_setfield(L, -2, "addNullable");

        // Static method: getNullableValue
        lua_pushcfunction(L, KeepAlive(SampleClass_static_getNullableValue));
        lua_setfield(L, -2, "getNullableValue");

        // Create metatable for type table (static properties)
        lua_newtable(L);
        lua_pushcfunction(L, KeepAlive(SampleClass_type__index));
        lua_setfield(L, -2, "__index");
        lua_pushcfunction(L, KeepAlive(SampleClass_type__newindex));
        lua_setfield(L, -2, "__newindex");
        lua_setmetatable(L, -2);

        lua_setglobal(L, "SampleClass");
    }

    private static int SampleClass__gc(lua_State L)
    {
        var ptr = lua_touserdata(L, 1);
        if (ptr != 0)
        {
            unsafe
            {
                var id = *(int*)ptr;
                RemoveObject<NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass>(id);
            }
        }
        return 0;
    }

    private static int SampleClass__index(lua_State L)
    {
        var key = lua_tostring(L, 2);
        if (key == null) { lua_pushnil(L); return 1; }

        var obj = GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass>(L, 1);
        if (obj == null) { lua_pushnil(L); return 1; }

        switch (key)
        {
            case "id":
                PushValue(L, obj.Id);
                return 1;
            case "name":
                PushValue(L, obj.Name);
                return 1;
            case "isActive":
                PushValue(L, obj.IsActive);
                return 1;
            case "value":
                PushValue(L, obj.Value);
                return 1;
            case "preciseValue":
                PushValue(L, obj.PreciseValue);
                return 1;
            case "nullableInt":
                if (obj.NullableInt.HasValue)
                    PushValue(L, obj.NullableInt.Value);
                else
                    lua_pushnil(L);
                return 1;
            case "nullableFloat":
                if (obj.NullableFloat.HasValue)
                    PushValue(L, obj.NullableFloat.Value);
                else
                    lua_pushnil(L);
                return 1;
            case "nullableBool":
                if (obj.NullableBool.HasValue)
                    PushValue(L, obj.NullableBool.Value);
                else
                    lua_pushnil(L);
                return 1;
            case "publicField":
                PushValue(L, obj.PublicField);
                return 1;
            case "publicStringField":
                PushValue(L, obj.PublicStringField);
                return 1;
            case "nullableLongField":
                if (obj.NullableLongField.HasValue)
                    PushValue(L, obj.NullableLongField.Value);
                else
                    lua_pushnil(L);
                return 1;
            case "getDoubleId":
                lua_pushcfunction(L, KeepAlive(SampleClass_method_getDoubleId));
                return 1;
            case "getGreeting":
                lua_pushcfunction(L, KeepAlive(SampleClass_method_getGreeting));
                return 1;
            case "setValue":
                lua_pushcfunction(L, KeepAlive(SampleClass_method_setValue));
                return 1;
            case "calculate":
                lua_pushcfunction(L, KeepAlive(SampleClass_method_calculate));
                return 1;
            case "clone":
                lua_pushcfunction(L, KeepAlive(SampleClass_method_clone));
                return 1;
            case "setNullableValue":
                lua_pushcfunction(L, KeepAlive(SampleClass_method_setNullableValue));
                return 1;
            case "multiplyByNullable":
                lua_pushcfunction(L, KeepAlive(SampleClass_method_multiplyByNullable));
                return 1;
            case "formatWithOptional":
                lua_pushcfunction(L, KeepAlive(SampleClass_method_formatWithOptional));
                return 1;
            case "customName":
                lua_pushcfunction(L, KeepAlive(SampleClass_method_customName));
                return 1;
            case "toString":
                lua_pushcfunction(L, KeepAlive(SampleClass_method_toString));
                return 1;
            case "getType":
                lua_pushcfunction(L, KeepAlive(SampleClass_method_getType));
                return 1;
            case "equals":
                lua_pushcfunction(L, KeepAlive(SampleClass_method_equals));
                return 1;
            case "getHashCode":
                lua_pushcfunction(L, KeepAlive(SampleClass_method_getHashCode));
                return 1;
            default:
                lua_pushnil(L);
                return 1;
        }
    }

    private static int SampleClass__newindex(lua_State L)
    {
        var key = lua_tostring(L, 2);
        if (key == null) return 0;

        var obj = GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass>(L, 1);
        if (obj == null) return 0;

        switch (key)
        {
            case "id":
                obj.Id = ToObject<int>(L, 3)!;
                break;
            case "name":
                obj.Name = ToObject<string>(L, 3)!;
                break;
            case "isActive":
                obj.IsActive = ToObject<bool>(L, 3)!;
                break;
            case "value":
                obj.Value = ToObject<float>(L, 3)!;
                break;
            case "preciseValue":
                obj.PreciseValue = ToObject<double>(L, 3)!;
                break;
            case "nullableInt":
                if (lua_isnil(L, 3) != 0)
                    obj.NullableInt = null;
                else
                    obj.NullableInt = ToObject<int>(L, 3)!;
                break;
            case "nullableFloat":
                if (lua_isnil(L, 3) != 0)
                    obj.NullableFloat = null;
                else
                    obj.NullableFloat = ToObject<float>(L, 3)!;
                break;
            case "nullableBool":
                if (lua_isnil(L, 3) != 0)
                    obj.NullableBool = null;
                else
                    obj.NullableBool = ToObject<bool>(L, 3)!;
                break;
            case "publicField":
                obj.PublicField = ToObject<int>(L, 3)!;
                break;
            case "publicStringField":
                obj.PublicStringField = ToObject<string>(L, 3)!;
                break;
            case "nullableLongField":
                if (lua_isnil(L, 3) != 0)
                    obj.NullableLongField = null;
                else
                    obj.NullableLongField = ToObject<long>(L, 3)!;
                break;
        }
        return 0;
    }

    private static int SampleClass__tostring(lua_State L)
    {
        var obj = GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass>(L, 1);
        lua_pushstring(L, obj?.ToString() ?? "nil");
        return 1;
    }

    private static int SampleClass_new(lua_State L)
    {
        var argCount = lua_gettop(L);

        if (argCount == 0)
        {
            var obj = new NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass();
            PushObject(L, obj, "MT_SampleClass");
            return 1;
        }

        if (argCount == 2)
        {
            var arg0 = ToObject<int>(L, 1)!;
            var arg1 = ToObject<string>(L, 2)!;
            var obj = new NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass(arg0, arg1);
            PushObject(L, obj, "MT_SampleClass");
            return 1;
        }

        if (argCount == 2)
        {
            int? arg0;
            if (lua_isnil(L, 1) != 0)
                arg0 = null;
            else
                arg0 = ToObject<int>(L, 1)!;
            var arg1 = ToObject<string>(L, 2)!;
            var obj = new NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass(arg0, arg1);
            PushObject(L, obj, "MT_SampleClass");
            return 1;
        }

        if (argCount == 4)
        {
            var arg0 = ToObject<int>(L, 1)!;
            var arg1 = ToObject<string>(L, 2)!;
            var arg2 = ToObject<bool>(L, 3)!;
            var arg3 = ToObject<float>(L, 4)!;
            var obj = new NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass(arg0, arg1, arg2, arg3);
            PushObject(L, obj, "MT_SampleClass");
            return 1;
        }

        luaL_error(L, "Invalid arguments for SampleClass constructor");
        return 0;
    }

    private static int SampleClass_static_add(lua_State L)
    {
        var argCount = lua_gettop(L);

        if (argCount == 2)
        {
            var arg0 = ToObject<int>(L, 1)!;
            var arg1 = ToObject<int>(L, 2)!;
            var result = NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass.Add(arg0, arg1);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for add");
        return 0;
    }

    private static int SampleClass_static_concat(lua_State L)
    {
        var argCount = lua_gettop(L);

        if (argCount == 2)
        {
            var arg0 = ToObject<string>(L, 1)!;
            var arg1 = ToObject<string>(L, 2)!;
            var result = NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass.Concat(arg0, arg1);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for concat");
        return 0;
    }

    private static int SampleClass_static_incrementCounter(lua_State L)
    {
        var argCount = lua_gettop(L);

        if (argCount == 0)
        {
            NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass.IncrementCounter();
            return 0;
        }

        luaL_error(L, "Invalid arguments for incrementCounter");
        return 0;
    }

    private static int SampleClass_static_addNullable(lua_State L)
    {
        var argCount = lua_gettop(L);

        if (argCount == 2)
        {
            int? arg0;
            if (lua_isnil(L, 1) != 0)
                arg0 = null;
            else
                arg0 = ToObject<int>(L, 1)!;
            int? arg1;
            if (lua_isnil(L, 2) != 0)
                arg1 = null;
            else
                arg1 = ToObject<int>(L, 2)!;
            var result = NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass.AddNullable(arg0, arg1);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for addNullable");
        return 0;
    }

    private static int SampleClass_static_getNullableValue(lua_State L)
    {
        var argCount = lua_gettop(L);

        if (argCount == 2)
        {
            var arg0 = ToObject<bool>(L, 1)!;
            var arg1 = ToObject<int>(L, 2)!;
            var result = NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass.GetNullableValue(arg0, arg1);
            if (result.HasValue)
                PushValue(L, result.Value);
            else
                lua_pushnil(L);
            return 1;
        }

        luaL_error(L, "Invalid arguments for getNullableValue");
        return 0;
    }

    private static int SampleClass_method_getDoubleId(lua_State L)
    {
        var argCount = lua_gettop(L) - 1; // First arg is self

        var self = GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected SampleClass as first argument");
            return 0;
        }

        if (argCount == 0)
        {
            var result = self.GetDoubleId();
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for getDoubleId");
        return 0;
    }

    private static int SampleClass_method_getGreeting(lua_State L)
    {
        var argCount = lua_gettop(L) - 1; // First arg is self

        var self = GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected SampleClass as first argument");
            return 0;
        }

        if (argCount == 1)
        {
            var arg0 = ToObject<string>(L, 2)!;
            var result = self.GetGreeting(arg0);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for getGreeting");
        return 0;
    }

    private static int SampleClass_method_setValue(lua_State L)
    {
        var argCount = lua_gettop(L) - 1; // First arg is self

        var self = GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected SampleClass as first argument");
            return 0;
        }

        if (argCount == 1)
        {
            var arg0 = ToObject<float>(L, 2)!;
            self.SetValue(arg0);
            return 0;
        }

        luaL_error(L, "Invalid arguments for setValue");
        return 0;
    }

    private static int SampleClass_method_calculate(lua_State L)
    {
        var argCount = lua_gettop(L) - 1; // First arg is self

        var self = GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected SampleClass as first argument");
            return 0;
        }

        if (argCount == 3)
        {
            var arg0 = ToObject<float>(L, 2)!;
            var arg1 = ToObject<float>(L, 3)!;
            var arg2 = ToObject<bool>(L, 4)!;
            var result = self.Calculate(arg0, arg1, arg2);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for calculate");
        return 0;
    }

    private static int SampleClass_method_clone(lua_State L)
    {
        var argCount = lua_gettop(L) - 1; // First arg is self

        var self = GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected SampleClass as first argument");
            return 0;
        }

        if (argCount == 0)
        {
            var result = self.Clone();
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for clone");
        return 0;
    }

    private static int SampleClass_method_setNullableValue(lua_State L)
    {
        var argCount = lua_gettop(L) - 1; // First arg is self

        var self = GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected SampleClass as first argument");
            return 0;
        }

        if (argCount == 1)
        {
            float? arg0;
            if (lua_isnil(L, 2) != 0)
                arg0 = null;
            else
                arg0 = ToObject<float>(L, 2)!;
            self.SetNullableValue(arg0);
            return 0;
        }

        luaL_error(L, "Invalid arguments for setNullableValue");
        return 0;
    }

    private static int SampleClass_method_multiplyByNullable(lua_State L)
    {
        var argCount = lua_gettop(L) - 1; // First arg is self

        var self = GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected SampleClass as first argument");
            return 0;
        }

        if (argCount == 1)
        {
            int? arg0;
            if (lua_isnil(L, 2) != 0)
                arg0 = null;
            else
                arg0 = ToObject<int>(L, 2)!;
            var result = self.MultiplyByNullable(arg0);
            if (result.HasValue)
                PushValue(L, result.Value);
            else
                lua_pushnil(L);
            return 1;
        }

        luaL_error(L, "Invalid arguments for multiplyByNullable");
        return 0;
    }

    private static int SampleClass_method_formatWithOptional(lua_State L)
    {
        var argCount = lua_gettop(L) - 1; // First arg is self

        var self = GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected SampleClass as first argument");
            return 0;
        }

        if (argCount == 2)
        {
            var arg0 = ToObject<string>(L, 2)!;
            var arg1 = ToObject<string>(L, 3)!;
            var result = self.FormatWithOptional(arg0, arg1);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for formatWithOptional");
        return 0;
    }

    private static int SampleClass_method_customName(lua_State L)
    {
        var argCount = lua_gettop(L) - 1; // First arg is self

        var self = GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected SampleClass as first argument");
            return 0;
        }

        if (argCount == 0)
        {
            var result = self.MethodWithCustomName();
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for customName");
        return 0;
    }

    private static int SampleClass_method_toString(lua_State L)
    {
        var argCount = lua_gettop(L) - 1; // First arg is self

        var self = GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected SampleClass as first argument");
            return 0;
        }

        if (argCount == 0)
        {
            var result = self.ToString();
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for toString");
        return 0;
    }

    private static int SampleClass_method_getType(lua_State L)
    {
        var argCount = lua_gettop(L) - 1; // First arg is self

        var self = GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected SampleClass as first argument");
            return 0;
        }

        if (argCount == 0)
        {
            var result = self.GetType();
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for getType");
        return 0;
    }

    private static int SampleClass_method_equals(lua_State L)
    {
        var argCount = lua_gettop(L) - 1; // First arg is self

        var self = GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected SampleClass as first argument");
            return 0;
        }

        if (argCount == 1)
        {
            var arg0 = ToObject<object>(L, 2)!;
            var result = self.Equals(arg0);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for equals");
        return 0;
    }

    private static int SampleClass_method_getHashCode(lua_State L)
    {
        var argCount = lua_gettop(L) - 1; // First arg is self

        var self = GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected SampleClass as first argument");
            return 0;
        }

        if (argCount == 0)
        {
            var result = self.GetHashCode();
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for getHashCode");
        return 0;
    }

    private static int SampleClass_type__index(lua_State L)
    {
        var key = lua_tostring(L, 2);
        if (key == null) { lua_pushnil(L); return 1; }

        switch (key)
        {
            case "staticCounter":
                PushValue(L, NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass.StaticCounter);
                return 1;
            case "staticName":
                PushValue(L, NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass.StaticName);
                return 1;
            case "staticNullableDouble":
                if (NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass.StaticNullableDouble.HasValue)
                    PushValue(L, NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass.StaticNullableDouble.Value);
                else
                    lua_pushnil(L);
                return 1;
            default:
                lua_rawget(L, 1);
                return 1;
        }
    }

    private static int SampleClass_type__newindex(lua_State L)
    {
        var key = lua_tostring(L, 2);
        if (key == null) return 0;

        switch (key)
        {
            case "staticCounter":
                NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass.StaticCounter = ToObject<int>(L, 3)!;
                return 0;
            case "staticNullableDouble":
                if (lua_isnil(L, 3) != 0)
                    NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass.StaticNullableDouble = null;
                else
                    NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleClass.StaticNullableDouble = ToObject<double>(L, 3)!;
                return 0;
            default:
                lua_rawset(L, 1);
                return 0;
        }
    }

}
