// <auto-generated />
// This file is auto-generated by NFMWorld.LuaSourceGenerator.
// ReSharper disable All
#nullable enable

using LuaNET.LuaJIT;
using static LuaNET.LuaJIT.Lua;

namespace NFMWorld.LuaSourceGenerator.Test.Bindings;

public partial class LuaBindings
{
    // =========== Bindings for TypeWithMultiDimArray (TypeWithMultiDimArray) ===========
    private static void Register_TypeWithMultiDimArray(lua_State L)
    {
        RegisterMetatable<NFMWorld.LuaSourceGenerator.Test.TypeWithMultiDimArray>("MT_TypeWithMultiDimArray");

        // Create metatable for instances
        luaL_newmetatable(L, "MT_TypeWithMultiDimArray");

        // __gc metamethod
        lua_pushcfunction(L, KeepAlive(TypeWithMultiDimArray__gc));
        lua_setfield(L, -2, "__gc");

        // __index metamethod
        lua_pushcfunction(L, KeepAlive(TypeWithMultiDimArray__index));
        lua_setfield(L, -2, "__index");

        // __newindex metamethod
        lua_pushcfunction(L, KeepAlive(TypeWithMultiDimArray__newindex));
        lua_setfield(L, -2, "__newindex");

        // __tostring metamethod
        lua_pushcfunction(L, KeepAlive(TypeWithMultiDimArray__tostring));
        lua_setfield(L, -2, "__tostring");

        lua_pop(L, 1);

        // Create type table for TypeWithMultiDimArray
        lua_newtable(L);

        // Constructor: new()
        lua_pushcfunction(L, KeepAlive(TypeWithMultiDimArray_new));
        lua_setfield(L, -2, "new");

        // Static method: createMatrix
        lua_pushcfunction(L, KeepAlive(TypeWithMultiDimArray_static_createMatrix));
        lua_setfield(L, -2, "createMatrix");

        // Static method: createIdentityMatrix
        lua_pushcfunction(L, KeepAlive(TypeWithMultiDimArray_static_createIdentityMatrix));
        lua_setfield(L, -2, "createIdentityMatrix");

        lua_setglobal(L, "TypeWithMultiDimArray");
    }

    private static int TypeWithMultiDimArray__gc(lua_State L)
    {
        var ptr = lua_touserdata(L, 1);
        if (ptr != 0)
        {
            unsafe
            {
                var id = *(int*)ptr;
                RemoveObject<NFMWorld.LuaSourceGenerator.Test.TypeWithMultiDimArray>(id);
            }
        }
        return 0;
    }

    private static int TypeWithMultiDimArray__index(lua_State L)
    {
        var obj = GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.TypeWithMultiDimArray>(L, 1);
        if (obj == null) { lua_pushnil(L); return 1; }

        var key = lua_tostring(L, 2);
        if (key == null) { lua_pushnil(L); return 1; }

        switch (key)
        {
            case "matrix":
                PushValue(L, obj.Matrix);
                return 1;
            case "tensor":
                PushValue(L, obj.Tensor);
                return 1;
            case "initializeMatrix":
                lua_pushcfunction(L, KeepAlive(TypeWithMultiDimArray_method_initializeMatrix));
                return 1;
            case "getRows":
                lua_pushcfunction(L, KeepAlive(TypeWithMultiDimArray_method_getRows));
                return 1;
            case "getCols":
                lua_pushcfunction(L, KeepAlive(TypeWithMultiDimArray_method_getCols));
                return 1;
            case "getValueAt":
                lua_pushcfunction(L, KeepAlive(TypeWithMultiDimArray_method_getValueAt));
                return 1;
            case "setValueAt":
                lua_pushcfunction(L, KeepAlive(TypeWithMultiDimArray_method_setValueAt));
                return 1;
            case "sumAll":
                lua_pushcfunction(L, KeepAlive(TypeWithMultiDimArray_method_sumAll));
                return 1;
            case "getType":
                lua_pushcfunction(L, KeepAlive(TypeWithMultiDimArray_method_getType));
                return 1;
            case "toString":
                lua_pushcfunction(L, KeepAlive(TypeWithMultiDimArray_method_toString));
                return 1;
            case "equals":
                lua_pushcfunction(L, KeepAlive(TypeWithMultiDimArray_method_equals));
                return 1;
            case "getHashCode":
                lua_pushcfunction(L, KeepAlive(TypeWithMultiDimArray_method_getHashCode));
                return 1;
            default:
                lua_pushnil(L);
                return 1;
        }
    }

    private static int TypeWithMultiDimArray__newindex(lua_State L)
    {
        var obj = GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.TypeWithMultiDimArray>(L, 1);
        if (obj == null) return 0;

        var key = lua_tostring(L, 2);
        if (key == null) return 0;

        switch (key)
        {
            case "matrix":
                obj.Matrix = ToObject<int[,]>(L, 3)!;
                break;
            case "tensor":
                obj.Tensor = ToObject<float[,,]>(L, 3)!;
                break;
        }
        return 0;
    }

    private static int TypeWithMultiDimArray__tostring(lua_State L)
    {
        var obj = GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.TypeWithMultiDimArray>(L, 1);
        lua_pushstring(L, obj?.ToString() ?? "nil");
        return 1;
    }

    private static int TypeWithMultiDimArray_new(lua_State L)
    {
        var argCount = lua_gettop(L);

        if (argCount == 0)
        {
            var obj = new NFMWorld.LuaSourceGenerator.Test.TypeWithMultiDimArray();
            PushObject(L, obj, "MT_TypeWithMultiDimArray");
            return 1;
        }

        if (argCount == 1)
        {
            var arg0 = ToObject<int[,]>(L, 1)!;
            var obj = new NFMWorld.LuaSourceGenerator.Test.TypeWithMultiDimArray(arg0);
            PushObject(L, obj, "MT_TypeWithMultiDimArray");
            return 1;
        }

        if (argCount == 2)
        {
            var arg0 = ToObject<int>(L, 1)!;
            var arg1 = ToObject<int>(L, 2)!;
            var obj = new NFMWorld.LuaSourceGenerator.Test.TypeWithMultiDimArray(arg0, arg1);
            PushObject(L, obj, "MT_TypeWithMultiDimArray");
            return 1;
        }

        luaL_error(L, "Invalid arguments for TypeWithMultiDimArray constructor");
        return 0;
    }

    private static int TypeWithMultiDimArray_static_createMatrix(lua_State L)
    {
        var argCount = lua_gettop(L);

        if (argCount == 2)
        {
            var arg0 = ToObject<int>(L, 1)!;
            var arg1 = ToObject<int>(L, 2)!;
            var result = NFMWorld.LuaSourceGenerator.Test.TypeWithMultiDimArray.CreateMatrix(arg0, arg1);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for createMatrix");
        return 0;
    }

    private static int TypeWithMultiDimArray_static_createIdentityMatrix(lua_State L)
    {
        var argCount = lua_gettop(L);

        if (argCount == 1)
        {
            var arg0 = ToObject<int>(L, 1)!;
            var result = NFMWorld.LuaSourceGenerator.Test.TypeWithMultiDimArray.CreateIdentityMatrix(arg0);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for createIdentityMatrix");
        return 0;
    }

    private static int TypeWithMultiDimArray_method_initializeMatrix(lua_State L)
    {
        var argCount = lua_gettop(L) - 1; // First arg is self

        var self = GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.TypeWithMultiDimArray>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected TypeWithMultiDimArray as first argument");
            return 0;
        }

        if (argCount == 2)
        {
            var arg0 = ToObject<int>(L, 2)!;
            var arg1 = ToObject<int>(L, 3)!;
            self.InitializeMatrix(arg0, arg1);
            return 0;
        }

        luaL_error(L, "Invalid arguments for initializeMatrix");
        return 0;
    }

    private static int TypeWithMultiDimArray_method_getRows(lua_State L)
    {
        var argCount = lua_gettop(L) - 1; // First arg is self

        var self = GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.TypeWithMultiDimArray>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected TypeWithMultiDimArray as first argument");
            return 0;
        }

        if (argCount == 0)
        {
            var result = self.GetRows();
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for getRows");
        return 0;
    }

    private static int TypeWithMultiDimArray_method_getCols(lua_State L)
    {
        var argCount = lua_gettop(L) - 1; // First arg is self

        var self = GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.TypeWithMultiDimArray>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected TypeWithMultiDimArray as first argument");
            return 0;
        }

        if (argCount == 0)
        {
            var result = self.GetCols();
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for getCols");
        return 0;
    }

    private static int TypeWithMultiDimArray_method_getValueAt(lua_State L)
    {
        var argCount = lua_gettop(L) - 1; // First arg is self

        var self = GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.TypeWithMultiDimArray>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected TypeWithMultiDimArray as first argument");
            return 0;
        }

        if (argCount == 2)
        {
            var arg0 = ToObject<int>(L, 2)!;
            var arg1 = ToObject<int>(L, 3)!;
            var result = self.GetValueAt(arg0, arg1);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for getValueAt");
        return 0;
    }

    private static int TypeWithMultiDimArray_method_setValueAt(lua_State L)
    {
        var argCount = lua_gettop(L) - 1; // First arg is self

        var self = GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.TypeWithMultiDimArray>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected TypeWithMultiDimArray as first argument");
            return 0;
        }

        if (argCount == 3)
        {
            var arg0 = ToObject<int>(L, 2)!;
            var arg1 = ToObject<int>(L, 3)!;
            var arg2 = ToObject<int>(L, 4)!;
            self.SetValueAt(arg0, arg1, arg2);
            return 0;
        }

        luaL_error(L, "Invalid arguments for setValueAt");
        return 0;
    }

    private static int TypeWithMultiDimArray_method_sumAll(lua_State L)
    {
        var argCount = lua_gettop(L) - 1; // First arg is self

        var self = GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.TypeWithMultiDimArray>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected TypeWithMultiDimArray as first argument");
            return 0;
        }

        if (argCount == 0)
        {
            var result = self.SumAll();
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for sumAll");
        return 0;
    }

    private static int TypeWithMultiDimArray_method_getType(lua_State L)
    {
        var argCount = lua_gettop(L) - 1; // First arg is self

        var self = GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.TypeWithMultiDimArray>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected TypeWithMultiDimArray as first argument");
            return 0;
        }

        if (argCount == 0)
        {
            var result = self.GetType();
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for getType");
        return 0;
    }

    private static int TypeWithMultiDimArray_method_toString(lua_State L)
    {
        var argCount = lua_gettop(L) - 1; // First arg is self

        var self = GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.TypeWithMultiDimArray>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected TypeWithMultiDimArray as first argument");
            return 0;
        }

        if (argCount == 0)
        {
            var result = self.ToString();
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for toString");
        return 0;
    }

    private static int TypeWithMultiDimArray_method_equals(lua_State L)
    {
        var argCount = lua_gettop(L) - 1; // First arg is self

        var self = GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.TypeWithMultiDimArray>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected TypeWithMultiDimArray as first argument");
            return 0;
        }

        if (argCount == 1)
        {
            object? arg0;
            if (lua_isnil(L, 2) != 0)
                arg0 = null;
            else
                arg0 = ToObject<object>(L, 2)!;
            var result = self.Equals(arg0);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for equals");
        return 0;
    }

    private static int TypeWithMultiDimArray_method_getHashCode(lua_State L)
    {
        var argCount = lua_gettop(L) - 1; // First arg is self

        var self = GetObjectFromStack<NFMWorld.LuaSourceGenerator.Test.TypeWithMultiDimArray>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected TypeWithMultiDimArray as first argument");
            return 0;
        }

        if (argCount == 0)
        {
            var result = self.GetHashCode();
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for getHashCode");
        return 0;
    }

}
