// <auto-generated />
// This file is auto-generated by NFMWorld.LuaSourceGenerator.
// ReSharper disable All
#nullable enable

using LuaNET.LuaJIT;
using static LuaNET.LuaJIT.Lua;
using NFMWorld.LuaSourceGenerator.Test.TestBindings;

namespace NFMWorld.LuaSourceGenerator.Test.TestBindings;

public partial class LuaBindings
{
    // =========== Bindings for Vector3Struct (Vec3) ===========
    private static void Register_Vector3Struct(lua_State L)
    {
        RegisterMetatable<NFMWorld.LuaSourceGenerator.Test.SampleTypes.Vector3Struct>("MT_Vector3Struct");

        // Create metatable for instances
        luaL_newmetatable(L, "MT_Vector3Struct");

        // __gc metamethod
        lua_pushcfunction(L, KeepAlive(Vector3Struct__gc));
        lua_setfield(L, -2, "__gc");

        // __index metamethod
        lua_pushcfunction(L, KeepAlive(Vector3Struct__index));
        lua_setfield(L, -2, "__index");

        // __newindex metamethod
        lua_pushcfunction(L, KeepAlive(Vector3Struct__newindex));
        lua_setfield(L, -2, "__newindex");

        // Operator: __add
        lua_pushcfunction(L, KeepAlive(Vector3Struct_op_op_Addition));
        lua_setfield(L, -2, "__add");

        // Operator: __sub
        lua_pushcfunction(L, KeepAlive(Vector3Struct_op_op_Subtraction));
        lua_setfield(L, -2, "__sub");

        // Operator: __mul
        lua_pushcfunction(L, KeepAlive(Vector3Struct_op_op_Multiply));
        lua_setfield(L, -2, "__mul");

        // Operator: __unm
        lua_pushcfunction(L, KeepAlive(Vector3Struct_op_op_UnaryNegation));
        lua_setfield(L, -2, "__unm");

        // __tostring metamethod
        lua_pushcfunction(L, KeepAlive(Vector3Struct__tostring));
        lua_setfield(L, -2, "__tostring");

        lua_pop(L, 1);

        // Create type table for Vec3
        lua_newtable(L);

        // Constructor: new()
        lua_pushcfunction(L, KeepAlive(Vector3Struct_new));
        lua_setfield(L, -2, "new");

        // Static method: cross
        lua_pushcfunction(L, KeepAlive(Vector3Struct_static_cross));
        lua_setfield(L, -2, "cross");

        // Static method: dot
        lua_pushcfunction(L, KeepAlive(Vector3Struct_static_dot));
        lua_setfield(L, -2, "dot");

        // Static method: fromVec2
        lua_pushcfunction(L, KeepAlive(Vector3Struct_static_fromVec2));
        lua_setfield(L, -2, "fromVec2");

        // Create metatable for type table (static properties)
        lua_newtable(L);
        lua_pushcfunction(L, KeepAlive(Vector3Struct_type__index));
        lua_setfield(L, -2, "__index");
        lua_setmetatable(L, -2);

        lua_setglobal(L, "Vec3");
    }

    private static int Vector3Struct__gc(lua_State L)
    {
        var ptr = lua_touserdata(L, 1);
        if (ptr != 0)
        {
            unsafe
            {
                var id = *(int*)ptr;
                RemoveObject<NFMWorld.LuaSourceGenerator.Test.SampleTypes.Vector3Struct>(id);
            }
        }
        return 0;
    }

    private static int Vector3Struct__index(lua_State L)
    {
        var key = lua_tostring(L, 2);
        if (key == null) { lua_pushnil(L); return 1; }

        var obj = GetStructFromStack<NFMWorld.LuaSourceGenerator.Test.SampleTypes.Vector3Struct>(L, 1);

        switch (key)
        {
            case "length":
                PushValue(L, obj.Length);
                return 1;
            case "x":
                PushValue(L, obj.X);
                return 1;
            case "y":
                PushValue(L, obj.Y);
                return 1;
            case "z":
                PushValue(L, obj.Z);
                return 1;
            case "normalized":
                lua_pushcfunction(L, KeepAlive(Vector3Struct_method_normalized));
                return 1;
            case "toVec2":
                lua_pushcfunction(L, KeepAlive(Vector3Struct_method_toVec2));
                return 1;
            case "toString":
                lua_pushcfunction(L, KeepAlive(Vector3Struct_method_toString));
                return 1;
            case "equals":
                lua_pushcfunction(L, KeepAlive(Vector3Struct_method_equals));
                return 1;
            case "getHashCode":
                lua_pushcfunction(L, KeepAlive(Vector3Struct_method_getHashCode));
                return 1;
            case "getType":
                lua_pushcfunction(L, KeepAlive(Vector3Struct_method_getType));
                return 1;
            default:
                lua_pushnil(L);
                return 1;
        }
    }

    private static int Vector3Struct__newindex(lua_State L)
    {
        var key = lua_tostring(L, 2);
        if (key == null) return 0;

        var obj = GetStructFromStack<NFMWorld.LuaSourceGenerator.Test.SampleTypes.Vector3Struct>(L, 1);

        switch (key)
        {
            case "x":
                obj.X = ToObject<float>(L, 3)!;
                UpdateStruct(L, 1, obj);
                break;
            case "y":
                obj.Y = ToObject<float>(L, 3)!;
                UpdateStruct(L, 1, obj);
                break;
            case "z":
                obj.Z = ToObject<float>(L, 3)!;
                UpdateStruct(L, 1, obj);
                break;
        }
        return 0;
    }

    private static int Vector3Struct__tostring(lua_State L)
    {
        var obj = GetStructFromStack<NFMWorld.LuaSourceGenerator.Test.SampleTypes.Vector3Struct>(L, 1);
        lua_pushstring(L, obj.ToString() ?? "");
        return 1;
    }

    private static int Vector3Struct_op_op_Addition(lua_State L)
    {
        var left = ToObject<NFMWorld.LuaSourceGenerator.Test.SampleTypes.Vector3Struct>(L, 1)!;
        var right = ToObject<NFMWorld.LuaSourceGenerator.Test.SampleTypes.Vector3Struct>(L, 2)!;
        var result = left + right;
        PushValue(L, result);
        return 1;
    }

    private static int Vector3Struct_op_op_Subtraction(lua_State L)
    {
        var left = ToObject<NFMWorld.LuaSourceGenerator.Test.SampleTypes.Vector3Struct>(L, 1)!;
        var right = ToObject<NFMWorld.LuaSourceGenerator.Test.SampleTypes.Vector3Struct>(L, 2)!;
        var result = left - right;
        PushValue(L, result);
        return 1;
    }

    private static int Vector3Struct_op_op_Multiply(lua_State L)
    {
        var left = ToObject<NFMWorld.LuaSourceGenerator.Test.SampleTypes.Vector3Struct>(L, 1)!;
        var right = ToObject<float>(L, 2)!;
        var result = left * right;
        PushValue(L, result);
        return 1;
    }

    private static int Vector3Struct_op_op_UnaryNegation(lua_State L)
    {
        var operand = ToObject<NFMWorld.LuaSourceGenerator.Test.SampleTypes.Vector3Struct>(L, 1)!;
        var result = -operand;
        PushValue(L, result);
        return 1;
    }

    private static int Vector3Struct_new(lua_State L)
    {
        var argCount = lua_gettop(L);

        if (argCount == 0)
        {
            var obj = new NFMWorld.LuaSourceGenerator.Test.SampleTypes.Vector3Struct();
            PushObject(L, obj, "MT_Vector3Struct");
            return 1;
        }

        if (argCount == 3)
        {
            var arg0 = ToObject<float>(L, 1)!;
            var arg1 = ToObject<float>(L, 2)!;
            var arg2 = ToObject<float>(L, 3)!;
            var obj = new NFMWorld.LuaSourceGenerator.Test.SampleTypes.Vector3Struct(arg0, arg1, arg2);
            PushObject(L, obj, "MT_Vector3Struct");
            return 1;
        }

        luaL_error(L, "Invalid arguments for Vector3Struct constructor");
        return 0;
    }

    private static int Vector3Struct_static_cross(lua_State L)
    {
        var argCount = lua_gettop(L);

        if (argCount == 2)
        {
            var arg0 = ToObject<NFMWorld.LuaSourceGenerator.Test.SampleTypes.Vector3Struct>(L, 1)!;
            var arg1 = ToObject<NFMWorld.LuaSourceGenerator.Test.SampleTypes.Vector3Struct>(L, 2)!;
            var result = NFMWorld.LuaSourceGenerator.Test.SampleTypes.Vector3Struct.Cross(arg0, arg1);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for cross");
        return 0;
    }

    private static int Vector3Struct_static_dot(lua_State L)
    {
        var argCount = lua_gettop(L);

        if (argCount == 2)
        {
            var arg0 = ToObject<NFMWorld.LuaSourceGenerator.Test.SampleTypes.Vector3Struct>(L, 1)!;
            var arg1 = ToObject<NFMWorld.LuaSourceGenerator.Test.SampleTypes.Vector3Struct>(L, 2)!;
            var result = NFMWorld.LuaSourceGenerator.Test.SampleTypes.Vector3Struct.Dot(arg0, arg1);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for dot");
        return 0;
    }

    private static int Vector3Struct_static_fromVec2(lua_State L)
    {
        var argCount = lua_gettop(L);

        if (argCount == 2)
        {
            var arg0 = ToObject<NFMWorld.LuaSourceGenerator.Test.SampleTypes.SampleStruct>(L, 1)!;
            var arg1 = ToObject<float>(L, 2)!;
            var result = NFMWorld.LuaSourceGenerator.Test.SampleTypes.Vector3Struct.FromVec2(arg0, arg1);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for fromVec2");
        return 0;
    }

    private static int Vector3Struct_method_normalized(lua_State L)
    {
        var argCount = lua_gettop(L) - 1; // First arg is self

        var self = GetStructFromStack<NFMWorld.LuaSourceGenerator.Test.SampleTypes.Vector3Struct>(L, 1);

        if (argCount == 0)
        {
            var result = self.Normalized();
            UpdateStruct(L, 1, self);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for normalized");
        return 0;
    }

    private static int Vector3Struct_method_toVec2(lua_State L)
    {
        var argCount = lua_gettop(L) - 1; // First arg is self

        var self = GetStructFromStack<NFMWorld.LuaSourceGenerator.Test.SampleTypes.Vector3Struct>(L, 1);

        if (argCount == 0)
        {
            var result = self.ToVec2();
            UpdateStruct(L, 1, self);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for toVec2");
        return 0;
    }

    private static int Vector3Struct_method_toString(lua_State L)
    {
        var argCount = lua_gettop(L) - 1; // First arg is self

        var self = GetStructFromStack<NFMWorld.LuaSourceGenerator.Test.SampleTypes.Vector3Struct>(L, 1);

        if (argCount == 0)
        {
            var result = self.ToString();
            UpdateStruct(L, 1, self);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for toString");
        return 0;
    }

    private static int Vector3Struct_method_equals(lua_State L)
    {
        var argCount = lua_gettop(L) - 1; // First arg is self

        var self = GetStructFromStack<NFMWorld.LuaSourceGenerator.Test.SampleTypes.Vector3Struct>(L, 1);

        if (argCount == 1)
        {
            var arg0 = ToObject<object>(L, 2)!;
            var result = self.Equals(arg0);
            UpdateStruct(L, 1, self);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for equals");
        return 0;
    }

    private static int Vector3Struct_method_getHashCode(lua_State L)
    {
        var argCount = lua_gettop(L) - 1; // First arg is self

        var self = GetStructFromStack<NFMWorld.LuaSourceGenerator.Test.SampleTypes.Vector3Struct>(L, 1);

        if (argCount == 0)
        {
            var result = self.GetHashCode();
            UpdateStruct(L, 1, self);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for getHashCode");
        return 0;
    }

    private static int Vector3Struct_method_getType(lua_State L)
    {
        var argCount = lua_gettop(L) - 1; // First arg is self

        var self = GetStructFromStack<NFMWorld.LuaSourceGenerator.Test.SampleTypes.Vector3Struct>(L, 1);

        if (argCount == 0)
        {
            var result = self.GetType();
            UpdateStruct(L, 1, self);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for getType");
        return 0;
    }

    private static int Vector3Struct_type__index(lua_State L)
    {
        var key = lua_tostring(L, 2);
        if (key == null) { lua_pushnil(L); return 1; }

        switch (key)
        {
            case "zero":
                PushValue(L, NFMWorld.LuaSourceGenerator.Test.SampleTypes.Vector3Struct.Zero);
                return 1;
            case "one":
                PushValue(L, NFMWorld.LuaSourceGenerator.Test.SampleTypes.Vector3Struct.One);
                return 1;
            default:
                lua_rawget(L, 1);
                return 1;
        }
    }

}
