namespace NFMWorld.LuaSourceGenerator;

internal class LuaBindingInitializeGenerator(IEnumerable<string> initializers, string @namespace)
{
    public string GenerateCode()
    {
        var sb = new IndentedStringBuilder();

        sb.AppendLine(
            $"""
            // <auto-generated />
            // This file is auto-generated by NFMWorld.LuaSourceGenerator.
            // ReSharper disable All
            #nullable enable

            using System.Runtime.CompilerServices;
            using System.Runtime.InteropServices;
            using LuaJIT;
            using static LuaJIT.Methods;

            namespace {@namespace};

            public unsafe partial class LuaBindings
            """);

        using (sb.Block())
        {
            sb.AppendLine("public static void Initialize(lua_State L)");
            using (sb.Block())
            {
                foreach (var initializer in initializers)
                {
                    sb.AppendLine(initializer);
                }

                sb.AppendLine(
                    """
                    Register(
                        L,
                        "OpaqueObject",
                        "OpaqueObject",
                        [
                            new luaL_RegManaged { name = "__gc", func = &Shared__gc },
                            new luaL_RegManaged { name = "__tostring", func = &Shared__tostring },
                        ],
                        null,
                        null
                    );
                    """
                );
            }
        }
        
        return sb.ToString();
    }
}