// <auto-generated />
// This file is auto-generated by NFMWorld.LuaSourceGenerator for test purposes.
// The base infrastructure (helper methods, storage, etc.) is in LuaBindingsBase.cs
// ReSharper disable All
#nullable enable

using LuaNET.LuaJIT;
using static LuaNET.LuaJIT.Lua;
using NFMWorld.LuaSourceGenerator.Test.SampleTypes;

namespace NFMWorld.LuaSourceGenerator.Test.TestBindings;

public partial class LuaBindings
{
    /// <summary>
    /// Initialize all Lua bindings for types marked with [LuaVisible]
    /// </summary>
    public static void Initialize(lua_State L)
    {
        Register_SampleClass(L);
        Register_SampleStruct(L);
        Register_Vector3Struct(L);
    }

    // =========== Bindings for SampleClass ===========
    private static void Register_SampleClass(lua_State L)
    {
        RegisterMetatable(typeof(SampleClass), "MT_SampleClass");

        // Create metatable for instances
        luaL_newmetatable(L, "MT_SampleClass");

        // __gc metamethod
        lua_pushcfunction(L, KeepAlive(SampleClass__gc));
        lua_setfield(L, -2, "__gc");

        // __index metamethod
        lua_pushcfunction(L, KeepAlive(SampleClass__index));
        lua_setfield(L, -2, "__index");

        // __newindex metamethod
        lua_pushcfunction(L, KeepAlive(SampleClass__newindex));
        lua_setfield(L, -2, "__newindex");

        // __tostring metamethod
        lua_pushcfunction(L, KeepAlive(SampleClass__tostring));
        lua_setfield(L, -2, "__tostring");

        lua_pop(L, 1);

        // Create type table for SampleClass
        lua_newtable(L);

        // Constructor: new()
        lua_pushcfunction(L, KeepAlive(SampleClass_new));
        lua_setfield(L, -2, "new");

        // Static method: add
        lua_pushcfunction(L, KeepAlive(SampleClass_static_add));
        lua_setfield(L, -2, "add");

        // Static method: concat
        lua_pushcfunction(L, KeepAlive(SampleClass_static_concat));
        lua_setfield(L, -2, "concat");

        // Static method: incrementCounter
        lua_pushcfunction(L, KeepAlive(SampleClass_static_incrementCounter));
        lua_setfield(L, -2, "incrementCounter");

        // Create metatable for type table (static properties)
        lua_newtable(L);
        lua_pushcfunction(L, KeepAlive(SampleClass_type__index));
        lua_setfield(L, -2, "__index");
        lua_pushcfunction(L, KeepAlive(SampleClass_type__newindex));
        lua_setfield(L, -2, "__newindex");
        lua_setmetatable(L, -2);

        lua_setglobal(L, "SampleClass");
    }

    private static int SampleClass__gc(lua_State L)
    {
        var ptr = lua_touserdata(L, 1);
        if (ptr != 0)
        {
            unsafe
            {
                var id = *(int*)ptr;
                RemoveObject(id);
            }
        }
        return 0;
    }

    private static int SampleClass__index(lua_State L)
    {
        var key = lua_tostring(L, 2);
        if (key == null) { lua_pushnil(L); return 1; }

        var obj = GetObjectFromStack<SampleClass>(L, 1);
        if (obj == null) { lua_pushnil(L); return 1; }

        switch (key)
        {
            case "id":
                PushValue(L, obj.Id);
                return 1;
            case "name":
                PushValue(L, obj.Name);
                return 1;
            case "isActive":
                PushValue(L, obj.IsActive);
                return 1;
            case "value":
                PushValue(L, obj.Value);
                return 1;
            case "preciseValue":
                PushValue(L, obj.PreciseValue);
                return 1;
            case "publicField":
                PushValue(L, obj.PublicField);
                return 1;
            case "publicStringField":
                PushValue(L, obj.PublicStringField);
                return 1;
            case "getDoubleId":
                lua_pushcfunction(L, KeepAlive(SampleClass_method_getDoubleId));
                return 1;
            case "getGreeting":
                lua_pushcfunction(L, KeepAlive(SampleClass_method_getGreeting));
                return 1;
            case "setValue":
                lua_pushcfunction(L, KeepAlive(SampleClass_method_setValue));
                return 1;
            case "calculate":
                lua_pushcfunction(L, KeepAlive(SampleClass_method_calculate));
                return 1;
            case "clone":
                lua_pushcfunction(L, KeepAlive(SampleClass_method_clone));
                return 1;
            case "customName":
                lua_pushcfunction(L, KeepAlive(SampleClass_method_customName));
                return 1;
            case "toString":
                lua_pushcfunction(L, KeepAlive(SampleClass_method_toString));
                return 1;
            default:
                lua_pushnil(L);
                return 1;
        }
    }

    private static int SampleClass__newindex(lua_State L)
    {
        var key = lua_tostring(L, 2);
        if (key == null) return 0;

        var obj = GetObjectFromStack<SampleClass>(L, 1);
        if (obj == null) return 0;

        switch (key)
        {
            case "id":
                obj.Id = (int)ToObject(L, 3, typeof(int))!;
                break;
            case "name":
                obj.Name = (string)ToObject(L, 3, typeof(string))!;
                break;
            case "isActive":
                obj.IsActive = (bool)ToObject(L, 3, typeof(bool))!;
                break;
            case "value":
                obj.Value = (float)ToObject(L, 3, typeof(float))!;
                break;
            case "preciseValue":
                obj.PreciseValue = (double)ToObject(L, 3, typeof(double))!;
                break;
            case "publicField":
                obj.PublicField = (int)ToObject(L, 3, typeof(int))!;
                break;
            case "publicStringField":
                obj.PublicStringField = (string)ToObject(L, 3, typeof(string))!;
                break;
        }
        return 0;
    }

    private static int SampleClass__tostring(lua_State L)
    {
        var obj = GetObjectFromStack<SampleClass>(L, 1);
        lua_pushstring(L, obj?.ToString() ?? "nil");
        return 1;
    }

    private static int SampleClass_new(lua_State L)
    {
        var argCount = lua_gettop(L);

        if (argCount == 0)
        {
            var obj = new SampleClass();
            PushObject(L, obj, "MT_SampleClass");
            return 1;
        }

        if (argCount == 2)
        {
            var arg0 = (int)ToObject(L, 1, typeof(int))!;
            var arg1 = (string)ToObject(L, 2, typeof(string))!;
            var obj = new SampleClass(arg0, arg1);
            PushObject(L, obj, "MT_SampleClass");
            return 1;
        }

        if (argCount == 4)
        {
            var arg0 = (int)ToObject(L, 1, typeof(int))!;
            var arg1 = (string)ToObject(L, 2, typeof(string))!;
            var arg2 = (bool)ToObject(L, 3, typeof(bool))!;
            var arg3 = (float)ToObject(L, 4, typeof(float))!;
            var obj = new SampleClass(arg0, arg1, arg2, arg3);
            PushObject(L, obj, "MT_SampleClass");
            return 1;
        }

        luaL_error(L, "Invalid arguments for SampleClass constructor");
        return 0;
    }

    private static int SampleClass_static_add(lua_State L)
    {
        var argCount = lua_gettop(L);

        if (argCount == 2)
        {
            var arg0 = (int)ToObject(L, 1, typeof(int))!;
            var arg1 = (int)ToObject(L, 2, typeof(int))!;
            var result = SampleClass.Add(arg0, arg1);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for add");
        return 0;
    }

    private static int SampleClass_static_concat(lua_State L)
    {
        var argCount = lua_gettop(L);

        if (argCount == 2)
        {
            var arg0 = (string)ToObject(L, 1, typeof(string))!;
            var arg1 = (string)ToObject(L, 2, typeof(string))!;
            var result = SampleClass.Concat(arg0, arg1);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for concat");
        return 0;
    }

    private static int SampleClass_static_incrementCounter(lua_State L)
    {
        var argCount = lua_gettop(L);

        if (argCount == 0)
        {
            SampleClass.IncrementCounter();
            return 0;
        }

        luaL_error(L, "Invalid arguments for incrementCounter");
        return 0;
    }

    private static int SampleClass_method_getDoubleId(lua_State L)
    {
        var argCount = lua_gettop(L) - 1;

        var self = GetObjectFromStack<SampleClass>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected SampleClass as first argument");
            return 0;
        }

        if (argCount == 0)
        {
            var result = self.GetDoubleId();
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for getDoubleId");
        return 0;
    }

    private static int SampleClass_method_getGreeting(lua_State L)
    {
        var argCount = lua_gettop(L) - 1;

        var self = GetObjectFromStack<SampleClass>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected SampleClass as first argument");
            return 0;
        }

        if (argCount == 1)
        {
            var arg0 = (string)ToObject(L, 2, typeof(string))!;
            var result = self.GetGreeting(arg0);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for getGreeting");
        return 0;
    }

    private static int SampleClass_method_setValue(lua_State L)
    {
        var argCount = lua_gettop(L) - 1;

        var self = GetObjectFromStack<SampleClass>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected SampleClass as first argument");
            return 0;
        }

        if (argCount == 1)
        {
            var arg0 = (float)ToObject(L, 2, typeof(float))!;
            self.SetValue(arg0);
            return 0;
        }

        luaL_error(L, "Invalid arguments for setValue");
        return 0;
    }

    private static int SampleClass_method_calculate(lua_State L)
    {
        var argCount = lua_gettop(L) - 1;

        var self = GetObjectFromStack<SampleClass>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected SampleClass as first argument");
            return 0;
        }

        if (argCount == 3)
        {
            var arg0 = (float)ToObject(L, 2, typeof(float))!;
            var arg1 = (float)ToObject(L, 3, typeof(float))!;
            var arg2 = (bool)ToObject(L, 4, typeof(bool))!;
            var result = self.Calculate(arg0, arg1, arg2);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for calculate");
        return 0;
    }

    private static int SampleClass_method_clone(lua_State L)
    {
        var argCount = lua_gettop(L) - 1;

        var self = GetObjectFromStack<SampleClass>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected SampleClass as first argument");
            return 0;
        }

        if (argCount == 0)
        {
            var result = self.Clone();
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for clone");
        return 0;
    }

    private static int SampleClass_method_customName(lua_State L)
    {
        var argCount = lua_gettop(L) - 1;

        var self = GetObjectFromStack<SampleClass>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected SampleClass as first argument");
            return 0;
        }

        if (argCount == 0)
        {
            var result = self.MethodWithCustomName();
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for customName");
        return 0;
    }

    private static int SampleClass_method_toString(lua_State L)
    {
        var argCount = lua_gettop(L) - 1;

        var self = GetObjectFromStack<SampleClass>(L, 1);
        if (self == null)
        {
            luaL_error(L, "Expected SampleClass as first argument");
            return 0;
        }

        if (argCount == 0)
        {
            var result = self.ToString();
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for toString");
        return 0;
    }

    private static int SampleClass_type__index(lua_State L)
    {
        var key = lua_tostring(L, 2);
        if (key == null) { lua_pushnil(L); return 1; }

        switch (key)
        {
            case "staticCounter":
                PushValue(L, SampleClass.StaticCounter);
                return 1;
            case "staticName":
                PushValue(L, SampleClass.StaticName);
                return 1;
            default:
                lua_rawget(L, 1);
                return 1;
        }
    }

    private static int SampleClass_type__newindex(lua_State L)
    {
        var key = lua_tostring(L, 2);
        if (key == null) return 0;

        switch (key)
        {
            case "staticCounter":
                SampleClass.StaticCounter = (int)ToObject(L, 3, typeof(int))!;
                return 0;
            default:
                lua_rawset(L, 1);
                return 0;
        }
    }

    // =========== Bindings for SampleStruct (Vec2) ===========
    private static void Register_SampleStruct(lua_State L)
    {
        RegisterMetatable(typeof(SampleStruct), "MT_SampleStruct");

        // Create metatable for instances
        luaL_newmetatable(L, "MT_SampleStruct");

        // __gc metamethod (cleanup storage)
        lua_pushcfunction(L, KeepAlive(SampleStruct__gc));
        lua_setfield(L, -2, "__gc");

        // __index metamethod
        lua_pushcfunction(L, KeepAlive(SampleStruct__index));
        lua_setfield(L, -2, "__index");

        // __newindex metamethod
        lua_pushcfunction(L, KeepAlive(SampleStruct__newindex));
        lua_setfield(L, -2, "__newindex");

        // Operator: __add
        lua_pushcfunction(L, KeepAlive(SampleStruct_op_Addition));
        lua_setfield(L, -2, "__add");

        // Operator: __sub
        lua_pushcfunction(L, KeepAlive(SampleStruct_op_Subtraction));
        lua_setfield(L, -2, "__sub");

        // Operator: __mul
        lua_pushcfunction(L, KeepAlive(SampleStruct_op_Multiply));
        lua_setfield(L, -2, "__mul");

        // Operator: __div
        lua_pushcfunction(L, KeepAlive(SampleStruct_op_Division));
        lua_setfield(L, -2, "__div");

        // Operator: __unm
        lua_pushcfunction(L, KeepAlive(SampleStruct_op_UnaryNegation));
        lua_setfield(L, -2, "__unm");

        // Operator: __eq
        lua_pushcfunction(L, KeepAlive(SampleStruct_op_Equality));
        lua_setfield(L, -2, "__eq");

        // __tostring metamethod
        lua_pushcfunction(L, KeepAlive(SampleStruct__tostring));
        lua_setfield(L, -2, "__tostring");

        lua_pop(L, 1);

        // Create type table for Vec2
        lua_newtable(L);

        // Constructor: new()
        lua_pushcfunction(L, KeepAlive(SampleStruct_new));
        lua_setfield(L, -2, "new");

        // Static method: distance
        lua_pushcfunction(L, KeepAlive(SampleStruct_static_distance));
        lua_setfield(L, -2, "distance");

        // Static method: fromAngle
        lua_pushcfunction(L, KeepAlive(SampleStruct_static_fromAngle));
        lua_setfield(L, -2, "fromAngle");

        // Static method: dot
        lua_pushcfunction(L, KeepAlive(SampleStruct_static_dot));
        lua_setfield(L, -2, "dot");

        // Create metatable for type table (static properties)
        lua_newtable(L);
        lua_pushcfunction(L, KeepAlive(SampleStruct_type__index));
        lua_setfield(L, -2, "__index");
        lua_setmetatable(L, -2);

        lua_setglobal(L, "Vec2");
    }

    private static int SampleStruct__gc(lua_State L)
    {
        var ptr = lua_touserdata(L, 1);
        if (ptr != 0)
        {
            unsafe
            {
                var id = *(int*)ptr;
                RemoveObject(id);
            }
        }
        return 0;
    }

    private static int SampleStruct__index(lua_State L)
    {
        var key = lua_tostring(L, 2);
        if (key == null) { lua_pushnil(L); return 1; }

        var obj = GetStructFromStack<SampleStruct>(L, 1);

        switch (key)
        {
            case "x":
                PushValue(L, obj.X);
                return 1;
            case "y":
                PushValue(L, obj.Y);
                return 1;
            case "length":
                PushValue(L, obj.Length);
                return 1;
            case "lengthSquared":
                PushValue(L, obj.LengthSquared);
                return 1;
            case "normalized":
                lua_pushcfunction(L, KeepAlive(SampleStruct_method_normalized));
                return 1;
            case "scale":
                lua_pushcfunction(L, KeepAlive(SampleStruct_method_scale));
                return 1;
            case "set":
                lua_pushcfunction(L, KeepAlive(SampleStruct_method_set));
                return 1;
            case "toString":
                lua_pushcfunction(L, KeepAlive(SampleStruct_method_toString));
                return 1;
            default:
                lua_pushnil(L);
                return 1;
        }
    }

    private static int SampleStruct__newindex(lua_State L)
    {
        var key = lua_tostring(L, 2);
        if (key == null) return 0;

        var obj = GetStructFromStack<SampleStruct>(L, 1);

        switch (key)
        {
            case "x":
                obj.X = (float)ToObject(L, 3, typeof(float))!;
                UpdateStruct(L, 1, obj);
                break;
            case "y":
                obj.Y = (float)ToObject(L, 3, typeof(float))!;
                UpdateStruct(L, 1, obj);
                break;
        }
        return 0;
    }

    private static int SampleStruct__tostring(lua_State L)
    {
        var obj = GetStructFromStack<SampleStruct>(L, 1);
        lua_pushstring(L, obj.ToString() ?? "");
        return 1;
    }

    private static int SampleStruct_new(lua_State L)
    {
        var argCount = lua_gettop(L);

        if (argCount == 0)
        {
            var obj = new SampleStruct();
            PushObject(L, obj, "MT_SampleStruct");
            return 1;
        }

        if (argCount == 2)
        {
            var arg0 = (float)ToObject(L, 1, typeof(float))!;
            var arg1 = (float)ToObject(L, 2, typeof(float))!;
            var obj = new SampleStruct(arg0, arg1);
            PushObject(L, obj, "MT_SampleStruct");
            return 1;
        }

        luaL_error(L, "Invalid arguments for SampleStruct constructor");
        return 0;
    }

    private static int SampleStruct_op_Addition(lua_State L)
    {
        var left = GetStructFromStack<SampleStruct>(L, 1);
        var right = GetStructFromStack<SampleStruct>(L, 2);
        var result = left + right;
        PushValue(L, result);
        return 1;
    }

    private static int SampleStruct_op_Subtraction(lua_State L)
    {
        var left = GetStructFromStack<SampleStruct>(L, 1);
        var right = GetStructFromStack<SampleStruct>(L, 2);
        var result = left - right;
        PushValue(L, result);
        return 1;
    }

    private static int SampleStruct_op_Multiply(lua_State L)
    {
        var left = GetStructFromStack<SampleStruct>(L, 1);
        var right = (float)lua_tonumber(L, 2);
        var result = left * right;
        PushValue(L, result);
        return 1;
    }

    private static int SampleStruct_op_Division(lua_State L)
    {
        var left = GetStructFromStack<SampleStruct>(L, 1);
        var right = (float)lua_tonumber(L, 2);
        var result = left / right;
        PushValue(L, result);
        return 1;
    }

    private static int SampleStruct_op_UnaryNegation(lua_State L)
    {
        var operand = GetStructFromStack<SampleStruct>(L, 1);
        var result = -operand;
        PushValue(L, result);
        return 1;
    }

    private static int SampleStruct_op_Equality(lua_State L)
    {
        var left = GetStructFromStack<SampleStruct>(L, 1);
        var right = GetStructFromStack<SampleStruct>(L, 2);
        lua_pushboolean(L, left == right ? 1 : 0);
        return 1;
    }

    private static int SampleStruct_static_distance(lua_State L)
    {
        var argCount = lua_gettop(L);

        if (argCount == 2)
        {
            var arg0 = GetStructFromStack<SampleStruct>(L, 1);
            var arg1 = GetStructFromStack<SampleStruct>(L, 2);
            var result = SampleStruct.Distance(arg0, arg1);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for distance");
        return 0;
    }

    private static int SampleStruct_static_fromAngle(lua_State L)
    {
        var argCount = lua_gettop(L);

        if (argCount == 1)
        {
            var arg0 = (float)ToObject(L, 1, typeof(float))!;
            var result = SampleStruct.FromAngle(arg0);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for fromAngle");
        return 0;
    }

    private static int SampleStruct_static_dot(lua_State L)
    {
        var argCount = lua_gettop(L);

        if (argCount == 2)
        {
            var arg0 = GetStructFromStack<SampleStruct>(L, 1);
            var arg1 = GetStructFromStack<SampleStruct>(L, 2);
            var result = SampleStruct.Dot(arg0, arg1);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for dot");
        return 0;
    }

    private static int SampleStruct_method_normalized(lua_State L)
    {
        var argCount = lua_gettop(L) - 1;

        var self = GetStructFromStack<SampleStruct>(L, 1);

        if (argCount == 0)
        {
            var result = self.Normalized();
            UpdateStruct(L, 1, self);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for normalized");
        return 0;
    }

    private static int SampleStruct_method_scale(lua_State L)
    {
        var argCount = lua_gettop(L) - 1;

        var self = GetStructFromStack<SampleStruct>(L, 1);

        if (argCount == 1)
        {
            var arg0 = (float)ToObject(L, 2, typeof(float))!;
            var result = self.Scale(arg0);
            UpdateStruct(L, 1, self);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for scale");
        return 0;
    }

    private static int SampleStruct_method_set(lua_State L)
    {
        var argCount = lua_gettop(L) - 1;

        var self = GetStructFromStack<SampleStruct>(L, 1);

        if (argCount == 2)
        {
            var arg0 = (float)ToObject(L, 2, typeof(float))!;
            var arg1 = (float)ToObject(L, 3, typeof(float))!;
            self.Set(arg0, arg1);
            UpdateStruct(L, 1, self);
            return 0;
        }

        luaL_error(L, "Invalid arguments for set");
        return 0;
    }

    private static int SampleStruct_method_toString(lua_State L)
    {
        var argCount = lua_gettop(L) - 1;

        var self = GetStructFromStack<SampleStruct>(L, 1);

        if (argCount == 0)
        {
            var result = self.ToString();
            UpdateStruct(L, 1, self);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for toString");
        return 0;
    }

    private static int SampleStruct_type__index(lua_State L)
    {
        var key = lua_tostring(L, 2);
        if (key == null) { lua_pushnil(L); return 1; }

        switch (key)
        {
            case "zero":
                PushValue(L, SampleStruct.Zero);
                return 1;
            case "one":
                PushValue(L, SampleStruct.One);
                return 1;
            case "unitX":
                PushValue(L, SampleStruct.UnitX);
                return 1;
            case "unitY":
                PushValue(L, SampleStruct.UnitY);
                return 1;
            default:
                lua_rawget(L, 1);
                return 1;
        }
    }

    // =========== Bindings for Vector3Struct (Vec3) ===========
    private static void Register_Vector3Struct(lua_State L)
    {
        RegisterMetatable(typeof(Vector3Struct), "MT_Vector3Struct");

        // Create metatable for instances
        luaL_newmetatable(L, "MT_Vector3Struct");

        // __gc metamethod (cleanup storage)
        lua_pushcfunction(L, KeepAlive(Vector3Struct__gc));
        lua_setfield(L, -2, "__gc");

        // __index metamethod
        lua_pushcfunction(L, KeepAlive(Vector3Struct__index));
        lua_setfield(L, -2, "__index");

        // __newindex metamethod
        lua_pushcfunction(L, KeepAlive(Vector3Struct__newindex));
        lua_setfield(L, -2, "__newindex");

        // Operator: __add
        lua_pushcfunction(L, KeepAlive(Vector3Struct_op_Addition));
        lua_setfield(L, -2, "__add");

        // Operator: __sub
        lua_pushcfunction(L, KeepAlive(Vector3Struct_op_Subtraction));
        lua_setfield(L, -2, "__sub");

        // Operator: __mul
        lua_pushcfunction(L, KeepAlive(Vector3Struct_op_Multiply));
        lua_setfield(L, -2, "__mul");

        // Operator: __unm
        lua_pushcfunction(L, KeepAlive(Vector3Struct_op_UnaryNegation));
        lua_setfield(L, -2, "__unm");

        // __tostring metamethod
        lua_pushcfunction(L, KeepAlive(Vector3Struct__tostring));
        lua_setfield(L, -2, "__tostring");

        lua_pop(L, 1);

        // Create type table for Vec3
        lua_newtable(L);

        // Constructor: new()
        lua_pushcfunction(L, KeepAlive(Vector3Struct_new));
        lua_setfield(L, -2, "new");

        // Static method: cross
        lua_pushcfunction(L, KeepAlive(Vector3Struct_static_cross));
        lua_setfield(L, -2, "cross");

        // Static method: dot
        lua_pushcfunction(L, KeepAlive(Vector3Struct_static_dot));
        lua_setfield(L, -2, "dot");

        // Static method: fromVec2
        lua_pushcfunction(L, KeepAlive(Vector3Struct_static_fromVec2));
        lua_setfield(L, -2, "fromVec2");

        // Create metatable for type table (static properties)
        lua_newtable(L);
        lua_pushcfunction(L, KeepAlive(Vector3Struct_type__index));
        lua_setfield(L, -2, "__index");
        lua_setmetatable(L, -2);

        lua_setglobal(L, "Vec3");
    }

    private static int Vector3Struct__gc(lua_State L)
    {
        var ptr = lua_touserdata(L, 1);
        if (ptr != 0)
        {
            unsafe
            {
                var id = *(int*)ptr;
                RemoveObject(id);
            }
        }
        return 0;
    }

    private static int Vector3Struct__index(lua_State L)
    {
        var key = lua_tostring(L, 2);
        if (key == null) { lua_pushnil(L); return 1; }

        var obj = GetStructFromStack<Vector3Struct>(L, 1);

        switch (key)
        {
            case "x":
                PushValue(L, obj.X);
                return 1;
            case "y":
                PushValue(L, obj.Y);
                return 1;
            case "z":
                PushValue(L, obj.Z);
                return 1;
            case "length":
                PushValue(L, obj.Length);
                return 1;
            case "normalized":
                lua_pushcfunction(L, KeepAlive(Vector3Struct_method_normalized));
                return 1;
            case "toVec2":
                lua_pushcfunction(L, KeepAlive(Vector3Struct_method_toVec2));
                return 1;
            case "toString":
                lua_pushcfunction(L, KeepAlive(Vector3Struct_method_toString));
                return 1;
            default:
                lua_pushnil(L);
                return 1;
        }
    }

    private static int Vector3Struct__newindex(lua_State L)
    {
        var key = lua_tostring(L, 2);
        if (key == null) return 0;

        var obj = GetStructFromStack<Vector3Struct>(L, 1);

        switch (key)
        {
            case "x":
                obj.X = (float)ToObject(L, 3, typeof(float))!;
                UpdateStruct(L, 1, obj);
                break;
            case "y":
                obj.Y = (float)ToObject(L, 3, typeof(float))!;
                UpdateStruct(L, 1, obj);
                break;
            case "z":
                obj.Z = (float)ToObject(L, 3, typeof(float))!;
                UpdateStruct(L, 1, obj);
                break;
        }
        return 0;
    }

    private static int Vector3Struct__tostring(lua_State L)
    {
        var obj = GetStructFromStack<Vector3Struct>(L, 1);
        lua_pushstring(L, obj.ToString() ?? "");
        return 1;
    }

    private static int Vector3Struct_new(lua_State L)
    {
        var argCount = lua_gettop(L);

        if (argCount == 0)
        {
            var obj = new Vector3Struct();
            PushObject(L, obj, "MT_Vector3Struct");
            return 1;
        }

        if (argCount == 3)
        {
            var arg0 = (float)ToObject(L, 1, typeof(float))!;
            var arg1 = (float)ToObject(L, 2, typeof(float))!;
            var arg2 = (float)ToObject(L, 3, typeof(float))!;
            var obj = new Vector3Struct(arg0, arg1, arg2);
            PushObject(L, obj, "MT_Vector3Struct");
            return 1;
        }

        luaL_error(L, "Invalid arguments for Vector3Struct constructor");
        return 0;
    }

    private static int Vector3Struct_op_Addition(lua_State L)
    {
        var left = GetStructFromStack<Vector3Struct>(L, 1);
        var right = GetStructFromStack<Vector3Struct>(L, 2);
        var result = left + right;
        PushValue(L, result);
        return 1;
    }

    private static int Vector3Struct_op_Subtraction(lua_State L)
    {
        var left = GetStructFromStack<Vector3Struct>(L, 1);
        var right = GetStructFromStack<Vector3Struct>(L, 2);
        var result = left - right;
        PushValue(L, result);
        return 1;
    }

    private static int Vector3Struct_op_Multiply(lua_State L)
    {
        var left = GetStructFromStack<Vector3Struct>(L, 1);
        var right = (float)lua_tonumber(L, 2);
        var result = left * right;
        PushValue(L, result);
        return 1;
    }

    private static int Vector3Struct_op_UnaryNegation(lua_State L)
    {
        var operand = GetStructFromStack<Vector3Struct>(L, 1);
        var result = -operand;
        PushValue(L, result);
        return 1;
    }

    private static int Vector3Struct_static_cross(lua_State L)
    {
        var argCount = lua_gettop(L);

        if (argCount == 2)
        {
            var arg0 = GetStructFromStack<Vector3Struct>(L, 1);
            var arg1 = GetStructFromStack<Vector3Struct>(L, 2);
            var result = Vector3Struct.Cross(arg0, arg1);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for cross");
        return 0;
    }

    private static int Vector3Struct_static_dot(lua_State L)
    {
        var argCount = lua_gettop(L);

        if (argCount == 2)
        {
            var arg0 = GetStructFromStack<Vector3Struct>(L, 1);
            var arg1 = GetStructFromStack<Vector3Struct>(L, 2);
            var result = Vector3Struct.Dot(arg0, arg1);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for dot");
        return 0;
    }

    private static int Vector3Struct_static_fromVec2(lua_State L)
    {
        var argCount = lua_gettop(L);

        if (argCount == 2)
        {
            var arg0 = GetStructFromStack<SampleStruct>(L, 1);
            var arg1 = (float)ToObject(L, 2, typeof(float))!;
            var result = Vector3Struct.FromVec2(arg0, arg1);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for fromVec2");
        return 0;
    }

    private static int Vector3Struct_method_normalized(lua_State L)
    {
        var argCount = lua_gettop(L) - 1;

        var self = GetStructFromStack<Vector3Struct>(L, 1);

        if (argCount == 0)
        {
            var result = self.Normalized();
            UpdateStruct(L, 1, self);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for normalized");
        return 0;
    }

    private static int Vector3Struct_method_toVec2(lua_State L)
    {
        var argCount = lua_gettop(L) - 1;

        var self = GetStructFromStack<Vector3Struct>(L, 1);

        if (argCount == 0)
        {
            var result = self.ToVec2();
            UpdateStruct(L, 1, self);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for toVec2");
        return 0;
    }

    private static int Vector3Struct_method_toString(lua_State L)
    {
        var argCount = lua_gettop(L) - 1;

        var self = GetStructFromStack<Vector3Struct>(L, 1);

        if (argCount == 0)
        {
            var result = self.ToString();
            UpdateStruct(L, 1, self);
            PushValue(L, result);
            return 1;
        }

        luaL_error(L, "Invalid arguments for toString");
        return 0;
    }

    private static int Vector3Struct_type__index(lua_State L)
    {
        var key = lua_tostring(L, 2);
        if (key == null) { lua_pushnil(L); return 1; }

        switch (key)
        {
            case "zero":
                PushValue(L, Vector3Struct.Zero);
                return 1;
            case "one":
                PushValue(L, Vector3Struct.One);
                return 1;
            default:
                lua_rawget(L, 1);
                return 1;
        }
    }
}
